### ISSUE TITLE
Unable to login on XVA

### ISSUE THREAD

**Issue by alcaraz73** [Jarli01/xenorchestra_installer#100]
Tried using xoce/xoce (lowercase and uppercase), using console and SSH.

HTTP not working neither.

Do I need to change a config?

**Comment by Jarli01** [comment]
Can you answer the questions in the template as well as provide a screenshot. You shouldn't have to make any changes.

**Comment by alcaraz73** [comment]
Thanks,

Unable to login on XVA

**To Reproduce**
Steps to reproduce the behavior:
1. Connect using Putty
2. Login as: XOCE (tried uppercase and lowercase)
3. XOCE@x.x.x.x's password: XOCE (tried uppercase and lowercase)
4. Access denied
5. Same result using Console

Expected to get access.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop/Server details (please complete the following information):**
 - OS: XCP-ng 8.2
 - Browser: Putty
 - Version: 

* Is this a fresh install or an upgrade?  
Yes, XVA downloaded today.
* Version of XOCE server and web interface you're running
* What OS is XOCE running on?
* A link to the ISO you've used as the server (so we can verify/troubleshoot)
https://nc.nl.tab.digital/s/WQmCwmH4e9EdTTA/download
* What method did you use to install XOCE (xo_install.sh, manual installation, etc)
XVA
![XOCE Putty](https://user-images.githubusercontent.com/37396661/133306403-27712345-4b46-4c57-a599-e1baf65f8c1e.png)

**Comment by Danp2** [comment]
@alcaraz73 Did you run `xoce-import.sh` or did you manually download / import the XVA?

**Comment by alcaraz73** [comment]
Downloaded, using script was dropping connections (The VM could not be imported; the end of the file was reached prematurely).

MD5 and SHA256 checksum verified.

Regards

**Comment by Jarli01** [comment]
The preconfigured package may not be working, I was working on getting that updated some time ago and never got back to it. 

The documented credentials on the main page though are for certain the credentials used when I setup that system, xoce and xoce, which will force you to change the password once you login. 

So if you've changed the password since getting this installed, I unfortunately can't help you. You could of course do a password reset or redownload the prepackaged install.

**Comment by Jarli01** [comment]
PC, the credentials are case sensitive and are all lowercase.

**Comment by alcaraz73** [comment]
Thanks for your effort, Dustin.  I solved using emergency mode.

Now it’s up and running.

**Comment by Jarli01** [comment]
Good deal, I'll close this then, if you need any other assistance don't hesitate to ask.
