### ISSUE TITLE
Debian 11 error loading Dashboard > Health

### ISSUE THREAD

**Issue by stevewest15** [Jarli01/xenorchestra_installer#103]
**Describe the bug**
On a new Debian GNU/Linux 11 (bullseye) ran the install script and was able to access XO via browser. However when I try to visit Dashboard > Health, the web browser returns "an error has occurred". 

**To Reproduce**
1. Go to "Dashboard" drop-down menu
2. Click on "Health"
3. The page loads with "an error has occurred"

**Expected behavior**
Should load up the XO Health page displaying the health of the pools, vms, etc.

**Screenshots**
Please see attached screenshot xo_health_page_error.png
![xo_health_page_error](https://user-images.githubusercontent.com/13159246/146431863-ec892814-8bcf-4daf-835b-9e0793b272c3.png)

**Desktop/Server details (please complete the following information):**
 - OS: Debian GNU/Linux 11 (bullseye)
 - Browser: Firefox v. 95.0.1
 - Browser: Chrome v. 96.0.4664.110

**Additional context**
I did not have this issue when running Debian 10.

**Confirm XOCE services are running**
Please run ```systemctl status xo-server.service``` and paste the resulting output below:
```# systemctl status xo-server.service
â xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Thu 2021-12-16 12:25:00 EST; 1h 36min ago
   Main PID: 323 (node)
      Tasks: 11 (limit: 77100)
     Memory: 294.6M
        CPU: 2min 37.888s
     CGroup: /system.slice/xo-server.service
             ââ323 /usr/local/bin/node ./dist/cli.mjs

Dec 16 13:42:23 XOCE xo-server[323]: 2021-12-16T18:42:23.373Z xo:main INFO + WebSocket connection (::ffff:10.10.>
Dec 16 13:43:48 XOCE xo-server[323]: 2021-12-16T18:43:48.312Z xo:main INFO - WebSocket connection (::ffff:10.10.>
Dec 16 13:43:48 XOCE xo-server[323]: 2021-12-16T18:43:48.328Z xo:main INFO + WebSocket connection (::ffff:10.10.>
Dec 16 13:43:48 XOCE xo-server[323]: 2021-12-16T18:43:48.395Z xo:main INFO - WebSocket connection (::ffff:10.10.>
Dec 16 13:43:49 XOCE xo-server[323]: 2021-12-16T18:43:49.420Z xo:main INFO + WebSocket connection (::ffff:10.10.>
Dec 16 13:58:14 XOCE xo-server[323]: 2021-12-16T18:58:14.074Z xo:main INFO - WebSocket connection (::ffff:10.10.>
Dec 16 13:58:14 XOCE xo-server[323]: 2021-12-16T18:58:14.097Z xo:main INFO - WebSocket connection (::ffff:10.10.>
Dec 16 13:58:34 XOCE xo-server[323]: 2021-12-16T18:58:34.968Z xo:main INFO + WebSocket connection (::ffff:10.10.>
Dec 16 13:59:24 XOCE xo-server[323]: 2021-12-16T18:59:24.838Z xo:main INFO + WebSocket connection (::ffff:10.10.>
Dec 16 14:00:51 XOCE xo-server[323]: 2021-12-16T19:00:51.140Z xo:main INFO - WebSocket connection (::ffff:10.10.>`
```
**Provide the output of journalctl logs**
Please run ```journalctl -u xo-server -f -n 50``` and paste the resulting output below:
```
journalctl -u xo-server -f -n 50
-- Journal begins at Thu 2021-12-16 11:35:05 EST. --
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.120Z xo:plugin INFO successfully register usage-report
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.120Z xo:plugin INFO successfully register web-hooks
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.120Z xo:plugin INFO successfully register backup-reports
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.120Z xo:plugin INFO successfully register transport-email
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.147Z xo:plugin INFO successfully register audit
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.147Z xo:plugin INFO successfully register load-balancer
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.147Z xo:plugin INFO successfully register perf-alert
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.171Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.176Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 12:25:17 XOCE xo-server[323]: 2021-12-16T17:25:17.248Z xo:plugin INFO successfully register sdn-controller
Dec 16 12:28:20 XOCE xo-server[323]: 2021-12-16T17:28:20.499Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 12:44:45 XOCE xo-server[323]: 2021-12-16T17:44:45.769Z xo:main INFO + Console proxy (aeadmin - ::ffff:10.10.10.55)
Dec 16 12:46:22 XOCE xo-server[323]: 2021-12-16T17:46:22.690Z xo:main INFO - Console proxy (aeadmin - ::ffff:10.10.10.55)
Dec 16 12:46:28 XOCE xo-server[323]: 2021-12-16T17:46:28.820Z xo:main INFO + Console proxy (aeadmin - ::ffff:10.10.10.55)
Dec 16 12:46:56 XOCE xo-server[323]: 2021-12-16T17:46:56.678Z xo:main INFO - Console proxy (aeadmin - ::ffff:10.10.10.55)
Dec 16 12:47:01 XOCE xo-server[323]: 2021-12-16T17:47:01.036Z xo:main INFO + Console proxy (aeadmin - ::ffff:10.10.10.55)
Dec 16 12:47:16 XOCE xo-server[323]: 2021-12-16T17:47:16.797Z xo:main INFO - Console proxy (aeadmin - ::ffff:10.10.10.55)
Dec 16 12:47:20 XOCE xo-server[323]: 2021-12-16T17:47:20.296Z xo:main INFO + Console proxy (aeadmin - ::ffff:10.10.10.55)
Dec 16 12:47:45 XOCE xo-server[323]: 2021-12-16T17:47:45.537Z xo:main INFO - Console proxy (aeadmin - ::ffff:10.10.10.55)
Dec 16 13:30:59 XOCE xo-server[323]: 2021-12-16T18:30:59.458Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:30:59 XOCE xo-server[323]: 2021-12-16T18:30:59.475Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:30:59 XOCE xo-server[323]: 2021-12-16T18:30:59.899Z xo:xo ERROR HTTP request error {
Dec 16 13:30:59 XOCE xo-server[323]:   error: NodeError: Premature close
Dec 16 13:30:59 XOCE xo-server[323]:       at ServerResponse.onclose (/opt/xen-orchestra/packages/xo-server/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:67:73)
Dec 16 13:30:59 XOCE xo-server[323]:       at ServerResponse.emit (node:events:402:35)
Dec 16 13:30:59 XOCE xo-server[323]:       at ServerResponse.emit (node:domain:475:12)
Dec 16 13:30:59 XOCE xo-server[323]:       at ServerResponse.patchedEmit [as emit] (/opt/xen-orchestra/@xen-orchestra/log/configure.js:118:17)
Dec 16 13:30:59 XOCE xo-server[323]:       at Socket.onServerResponseClose (node:_http_server:235:23)
Dec 16 13:30:59 XOCE xo-server[323]:       at Socket.emit (node:events:402:35)
Dec 16 13:30:59 XOCE xo-server[323]:       at Socket.emit (node:domain:475:12)
Dec 16 13:30:59 XOCE xo-server[323]:       at Socket.patchedEmit [as emit] (/opt/xen-orchestra/@xen-orchestra/log/configure.js:118:17)
Dec 16 13:30:59 XOCE xo-server[323]:       at TCP.<anonymous> (node:net:687:12)
Dec 16 13:30:59 XOCE xo-server[323]:       at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Dec 16 13:30:59 XOCE xo-server[323]: }
Dec 16 13:30:59 XOCE xo-server[323]: 2021-12-16T18:30:59.906Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:31:22 XOCE xo-server[323]: 2021-12-16T18:31:22.029Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:31:34 XOCE xo-server[323]: 2021-12-16T18:31:34.077Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:42:22 XOCE xo-server[323]: 2021-12-16T18:42:22.163Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:42:22 XOCE xo-server[323]: 2021-12-16T18:42:22.205Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:42:22 XOCE xo-server[323]: 2021-12-16T18:42:22.227Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:42:23 XOCE xo-server[323]: 2021-12-16T18:42:23.373Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:43:48 XOCE xo-server[323]: 2021-12-16T18:43:48.312Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:43:48 XOCE xo-server[323]: 2021-12-16T18:43:48.328Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:43:48 XOCE xo-server[323]: 2021-12-16T18:43:48.395Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:43:49 XOCE xo-server[323]: 2021-12-16T18:43:49.420Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:58:14 XOCE xo-server[323]: 2021-12-16T18:58:14.074Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:58:14 XOCE xo-server[323]: 2021-12-16T18:58:14.097Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:58:34 XOCE xo-server[323]: 2021-12-16T18:58:34.968Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 13:59:24 XOCE xo-server[323]: 2021-12-16T18:59:24.838Z xo:main INFO + WebSocket connection (::ffff:10.10.10.55)
Dec 16 14:00:51 XOCE xo-server[323]: 2021-12-16T19:00:51.140Z xo:main INFO - WebSocket connection (::ffff:10.10.10.55)`
```
**Provide answers to these questions:**
* Is this a fresh install or an upgrade? **Fresh install**
* Version of XOCE server and web interface you're running: Xen Orchestra, commit 24356 , xo-server 5.85.0 , xo-web 5.91.0
* What OS is XOCE running on? Debian 11
* A link to the ISO you've used as as the server (so we can verify/troubleshoot) [Debian 11 netinstall](https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-11.1.0-amd64-netinst.iso) with only ssh server & admin utilities installed
* What method did you use to install XOCE (xo_install.sh, manual installation, etc): On the clean Debian install, ran the install script `curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh | sudo bash`
* What specific XOCE page you're on, and what specific element you're interacting with to trigger the error: Dashboard > Health page
* If a stacktrace is provided in the error, include that too.
* Any errors that appear in your browser's error console: see console-export-2021-12-16_14-9-59.txt 
[console-export-2021-12-16_14-9-59.txt](https://github.com/Jarli01/xenorchestra_installer/files/7729851/console-export-2021-12-16_14-9-59.txt) attachment for errors outputted to browser console 
* Include what you've done so far in the installation, and if you got any error messages along the way: After I couldn't load the Health page, I tried re-running the XO install 
* Indicate whether or not you've manually edited any data directly: I only edited one file manually to setup the Debian network ( etc/network/interfaces )

Thank You,

SW

**Comment by Danp2** [comment]
> Dec 16 13:30:59 XOCE xo-server[323]: 2021-12-16T18:30:59.899Z xo:xo ERROR HTTP request error {
Dec 16 13:30:59 XOCE xo-server[323]:   error: NodeError: Premature close
Dec 16 13:30:59 XOCE xo-server[323]:       at ServerResponse.onclose (/opt/xen-orchestra/packages/xo-server/node_modules/readable-stream/lib/internal/streams/end-of-stream.js:67:73)
Dec 16 13:30:59 XOCE xo-server[323]:       at ServerResponse.emit (node:events:402:35)
Dec 16 13:30:59 XOCE xo-server[323]:       at ServerResponse.emit (node:domain:475:12)
Dec 16 13:30:59 XOCE xo-server[323]:       at ServerResponse.patchedEmit [as emit] (/opt/xen-orchestra/@xen-orchestra/log/configure.js:118:17)
Dec 16 13:30:59 XOCE xo-server[323]:       at Socket.onServerResponseClose (node:_http_server:235:23)
Dec 16 13:30:59 XOCE xo-server[323]:       at Socket.emit (node:events:402:35)
Dec 16 13:30:59 XOCE xo-server[323]:       at Socket.emit (node:domain:475:12)
Dec 16 13:30:59 XOCE xo-server[323]:       at Socket.patchedEmit [as emit] (/opt/xen-orchestra/@xen-orchestra/log/configure.js:118:17)
Dec 16 13:30:59 XOCE xo-server[323]:       at TCP.<anonymous> (node:net:687:12)
Dec 16 13:30:59 XOCE xo-server[323]:       at TCP.callbackTrampoline (node:internal/async_hooks:130:17)
Dec 16 13:30:59 XOCE xo-server[323]: }

I'm trying to replicate this issue now. What version of Node is active? Post the results of `node -v`

**Comment by Danp2** [comment]
> warning url-loader@1.1.2: Invalid bin field for "url-loader".

This is the only issue I encountered during the build process. XO appears to be running fine; no errors related to Dashboard > Health

> On the clean Debian install, ran the install script curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh | sudo bash

Can you elaborate on this. I know that `curl` and `sudo` are not installed by default in Debian, so you would have needed to install those manually.

FWIW, here are the steps I took --

- Logged in as root 
- Installed XenTools from ISO
- Installed curl with apt-get
- Issued the command `curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh |  bash
`

**Comment by stevewest15** [comment]
Hi @Danp2 ,

Thank you for your assistance! I forgot to mention I did have to install two packages on Debian 11 prior to running the XO install script as sudo and curl are required:

`apt-get install sudo curl`

Here are the versions that got installed of the above packages:

Package: curl
Version: 7.74.0-1.3+b1
Priority: optional
Section: web
Source: curl (7.74.0-1.3)
Maintainer: Alessandro Ghedini <ghedo@debian.org>

Package: sudo
Version: 1.9.5p2-3
Priority: optional
Section: admin
Maintainer: Sudo Maintainers <sudo@packages.debian.org>


In regards to node version, it's the following:

`root@XOCE:~# node -v
v16.13.1`

And did install XenTools from ISO on XO vm:

`Management agent 8.0.50-1 detected`

**Comment by Danp2** [comment]
Still not able to reproduce this on my end. Some thoughts / questions -

- Have you tried restarting the service (`sudo systemctl restart xo-server.service`)?
- You could try issuing the commands `yarn; yarn build` followed by the restart above
-  Were you logged in as root or a standard user?
- Can you replicate the issue on a new VM?

**Comment by stevewest15** [comment]
@Danp2 ,

Thank you for your assistance! Here is answers to your questions:

Have you tried restarting the service (sudo systemctl restart xo-server.service)? 
**Yes as well as rebooted VM**

You could try issuing the commands yarn; yarn build followed by the restart above
**I tried this but got an error (see below):**

root@XOCE:~# yarn
yarn install v1.22.17
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
Done in 0.12s.

root@XOCE:~# yarn build
yarn run v1.22.17
**error Couldn't find a package.json file in "/root"**
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.


Were you logged in as root or a standard user?
**I was logged in as root** 

Can you replicate the issue on a new VM?

**I did try doing it on a new VM and still was able to replicate the issue. I followed your steps as such:**

1. Install Debian 11 base plus ssh server and admin utilities
2. Logged in as root
3. Installed XenTools from ISO
4. Installed curl with apt-get
5. Issued the command curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh | bash
6. Logged in XO Dashboard and added 3 servers
7. Checked Health page (Dashboard > Health) and got the same error "an error has occurred"

**Comment by Danp2** [comment]
>  I tried this but got an error (see below):

This will only work if you are in the correct subdirectory. CD into /opt/xen-orchestra first.

> Logged in XO Dashboard and added 3 servers

Does the error only occur after adding the servers? Have you tried removing them one by one to see if the error goes away?

**Comment by Danp2** [comment]
In your original graphic, there's a yellow warning icon next to the Home link. I'm guessing that this appears whenever you add one of the problematic servers. I suggest investigating this further via the logs.

Does this issue only occur with Debian 11? Also, have you tried with XOA?

**Comment by stevewest15** [comment]
The yellow warning is about missing updates as we're on version 8.0 instead of the latest xcp-ng.

The issue only occurs on Debian 11. I have a XOCE on Debian 10 and it's able to load the Health dashboard with no issues. 

I'll try w/ XOA and report back.

**Comment by Danp2** [comment]
Just watched your video. It seems that during the process you switched a different SSH session and logged into the new Debian VM as "swadmin" instead of "root". This is different that what you described above.

Be sure to use the `latest` channel when you test with XOA.

**Comment by Danp2** [comment]
I'm guessing that XOA will work fine since it probably isn't using Debian 11 (I haven't confirmed this). You may need to manually build XO on Debian and then report your findings back on the forum so that they will be willing to investigate further.

**Comment by Danp2** [comment]
P.S. You'll likely be told to upgrade to a supported version of xcp-ng.

**Comment by Danp2** [comment]
@stevewest15 Looks like the latest XO commit may have fixed this issue. Please try rebuilding and let us know.

**Comment by stevewest15** [comment]
@Danp2 Thank you, yes I can confirm it's now fixed! Greatly appreciate all of the help!
