### ISSUE TITLE
Installation Script Issue

### ISSUE THREAD

**Issue by bambosd** [Jarli01/xenorchestra_installer#104]
Debian 11
-----------------

[info] Starting xo-server...
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open
 waiting for port to be open

[fail] Installation completed, but looks like there was a problem when starting xo-server/reading journalctl. Please see logs for more details

**Comment by Danp2** [comment]
@bambosd You may want to provide some additional details. FWIW, the script ran fine for me the other day when using Debian 11.1 netinstall ISO.

**Comment by bambosd** [comment]
Hello @Danp2 , i'm using Debian 11,2 netinstall which is the latest i found on website.
Then i did 3 trials: 
Debian VM on XCP-NG host with 4GB Ram - Failed
Debian VM on Virtual Box on Windows Host 4GB Ram - Failed
Debian VM on Virtual Box on another Windows Host 4GB Ram - Success (i don't know why)

Also i'm always trying to access the web server with the VM IP address on port 80, and it appears Apache web server info page, but not XOA web interface. I'm available to perform some more test if it would be helpful. Thanks.

**Comment by Danp2** [comment]
I think that you've posted this issue in the wrong repo. Did you mean to post [here](https://github.com/ronivay/XenOrchestraInstallerUpdater) instead?

**Comment by bambosd** [comment]
maybe, i'm sorry. but is very interesting to see this method also.
