### ISSUE TITLE
the console password is not the console password?

### ISSUE THREAD

**Issue by artlessknave** [Jarli01/xenorchestra_installer#105]
**Describe the bug**
the password and username is not:
Username: XOCE Password: XOCE
Username: XOCE Password: xoce
Username: xoce Password: XOCE
Username: xoce Password: xoce
Username: root Password: xoce
Username: root Password: XOCE
Username: root Password: root
Username: root Password: toor
Username: xoce Password: actual password
Username: root Password: actual password

the github page says :
Username: XOCE Password: XOCE
but the install script says:
Default UI credentials: admin@admin.net/admin
Default console credentials: xoce/xoce

I have yet to try the web credentials, because the first thing the install did was pick the wrong NIC, and now pfsense decided to give it an old IP that windows thinks is something else, so i cannot get to it or login to fix it, but that's not really relevant to the console password being different.

**To Reproduce**
install it. try to login with the passwords listed.

**Expected behavior**
I would expect the passwords given to...be valid?

**Screenshots**

**Desktop/Server details (please complete the following information):**
 - OS: windows10
 - Browser firefox
 - Version : of what?

**Additional context**

**Confirm XOCE services are running**
Please run ```systemctl status xo-server.service``` and paste the resulting output below. 

**Provide the output of journalctl logs**
Please run ```journalctl -u xo-server -f -n 50``` and paste the resulting output below. 

**Provide answers to these questions:**
* fresh install
* Version of XOCE server and web interface you're running
* What OS is XOCE running on? ubuntu 20.04.1 LTS , its the autoinstall
* Include what you've done so far in the installation, and if you got any error messages along the way.
 nothing, i cannot login
* Indicate whether or not you've manually edited any data directly.
 as i cannot login....nope.

**Comment by Danp2** [comment]
How are you trying to reach the console? If you are using anything other than XCP-ng Center, then I imagine that you would encounter the same issue with the IP address confusion.

**Comment by Jarli01** [comment]
How did you install this, I assume you downloaded the prepackaged build, correct?

**Comment by artlessknave** [comment]
this is the prepackaged build from the script listed on the "code" page (i have installed manually before, but I really like automatic, so was hoping it would work)

I am trying to connect from the official xoa, simple going into the console and typing in the password.
the IP address problems are, apparently, a quirk of the dhcp server in pfsense; annoying, but surmountable, i only mentioned that because it prevent me getting into the xoce web page, it doesn't affect the console login with xoa.

**Comment by Jarli01** [comment]
In order to test the appliance version that I setup some time ago, I'll have to get some free time to test. At initial login the system forces you to change the password, from 'xoce' to whatever you want. 

So unless I miss-entered the password at creation some months ago, the password was changed post installation within your environment. 

Can you provide the MD5 of the file you downloaded?

**Comment by artlessknave** [comment]
i Haven't changed anything yet, because I cant login to change it. that's the problem.
this is my environment, I control everything. the file was downloaded with the script from curl. I'm not sure how I would even get an md5 of it.
I might be able to hack it by going into single user and forcing it to change, but I haven't had a chance to do that just yet.
I was hoping there was just a typo on the website or something simple :|

**Comment by Jarli01** [comment]
> i Haven't changed anything yet, because I cant login to change it. that's the problem. this is my environment, I control everything. the file was downloaded with the script from curl. I'm not sure how I would even get an md5 of it. I might be able to hack it by going into single user and forcing it to change, but I haven't had a chance to do that just yet. I was hoping there was just a typo on the website or something simple :|

If you're using the curl method, **https://github.com/Jarli01/xenorchestra_installer#installation** then you installed Ubuntu or Debian as a VM on your XCP-NG hypervisor yourself, correct?

- If so, the credentials to login to the system are whatever you used during installation and I can't directly help you. There are means of jumping into recovery mode and resetting the password though. 

Or are you using the prepackaged version? https://github.com/Jarli01/xenorchestra_installer#prepacked-installation

**Comment by artlessknave** [comment]
i ran:
bash -c "$(curl -s https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xoce-import.sh)"
and it told me to login with xoce/xoce, which doesnt work. i did nothing else (because nothing else can be done), and clearly stated that i ran the prepackaged version, and that that version, which has no setup options, doesnt accept the password givem by either the script or whats listed on githun...

I don't know how to make that more clear. I have, previously, installed xoce with the semi-automated script method, but was specifically trying to use the prepackaged that is new, in the hope it would be easier. 

it's looking like its not going to be easier...

**Comment by artlessknave** [comment]
nevermind for now, I'm gonna nuke it, maybe something went wrong with the installer somewhere.

**Comment by artlessknave** [comment]
well. i give up. installing the scripted install instead.


[20:17 servername# bash -c "$(curl -s https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xoce-import.sh)"

Welcome to the XOCE auto-deploy script!

Network settings:
IP address? [dhcp]

Your XOCE installation will be started using DHCP

Importing XOCE VM…
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 61 1677M   61 1038M    0     0  5004k      0  0:05:43  0:03:32  0:02:11  289k
curl: (18) transfer closed with 670880409 bytes remaining to read


Auto deploy failed. Please contact us on https://github.com/Jarli01/xenorchestra_installer/issues for assistance.
Error:

 The VM could not be imported; the end of the file was reached prematurely.

**Comment by gostaex** [comment]
What password a console
xoce/xoce not work

**Comment by Jarli01** [comment]
For now, please boot into recovery mode and perform a password reset. I've not had a chance to validate what the issue is. Its possible that the password I misentered some time ago. 

The prepackaged build is something I setup to see if I can do it and has little to no support.
