### ISSUE TITLE
Ubntu Webinterface times out 

### ISSUE THREAD

**Issue by sojab0on** [Jarli01/xenorchestra_installer#107]
I setup a clean installed Debian 10.3 vm and run the installer

At the end it fails 
```
error Couldn't find a package.json file in "/opt"
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
bash: line 54: cd: packages/xo-server: No such file or directory
cp: cannot stat 'sample.config.toml': No such file or directory
ls: cannot access '/opt/xen-orchestra/packages/xo-server-*': No such file or directory
```
the /opt folder is empty so somewhere where it needs to create it it doesnt create the folders

**Comment by Jarli01** [comment]
Please fill out the ticket template.

**Comment by Danp2** [comment]
It sounds like the `git clone` on line 48 is failing. We would know more if you showed the complete log.

**Comment by sojab0on** [comment]
I have rebuild the vm with ubuntu server 20.04.4 lts 

Now the server runs but its unreachable from the network the vm gets an ip systemctl shows its running 

even disabled UFW to check if that blocks connection 

VM has ip xxx.xx.x.188 from the normal lan network 
and a ip from the mgmt net on .10


If i hop on a server in the management network it can connect to the XOA-CE web interface from the vm but even with hard set ips in the netplan its unreacable 


altough the Dhcp server sees the request from the vm come in and assigns a ip to it 

Is it a config error or the server  that doesnt accept a connection

**Comment by Danp2** [comment]
This sounds to me like a configuration issue on your end. How many virtual nics do you have defined on this VM? Does it work correctly if you only have one?
