### ISSUE TITLE
Documentation - SSL setup requires additional changes to xo-server.toml

### ISSUE THREAD

**Issue by sutley** [Jarli01/xenorchestra_installer#108]
When setting up the self-signed SSL I was running into an issue where XOCE would become inaccessible after configuring the certificate. After looking at the Vates sample.config.toml I realized a few things were missing:

redirectToHttps = true (In "Configuration of the embedded HTTP Server")
[[http.listen]] (In "Basic HTTPS" Section)

After adding these + the listed changes in the README to xo-server.toml, the server now has its SSL cert applied and the redirect working. Might I suggest adding these two updates to the README..

Haven't used Github in a few years, so if this is in the wrong spot, sorry.

**Comment by Jarli01** [comment]
Sorry for just now getting to this, can you post the changes as they need to be changed. Don't have a system in front of me to do this with at the moment. 

Thanks!
