### ISSUE TITLE
error build 

### ISSUE THREAD

**Issue by rezasafaei70** [Jarli01/xenorchestra_installer#110]
I'm building, I don't know exactly what happened that my build is getting the following error. My executable command is yarn build

node -v  :
18.12.0

yarn -v :
1.22.19 
#

> 
> ParseError: 'import' and 'export' may appear only with 'sourceType: module'
>     at formatError (/home/boshra/projects/test/xen-orchestra/node_modules/gulp-cli/lib/versioned/^4.0.0/format-error.js:21:10)
>     at Gulp.<anonymous> (/home/boshra/projects/test/xen-orchestra/node_modules/gulp-cli/lib/versioned/^4.0.0/log/events.js:33:15)
>     at Gulp.emit (node:events:525:35)
>     at Gulp.emit (node:domain:489:12)
>     at Object.error (/home/boshra/projects/test/xen-orchestra/node_modules/undertaker/lib/helpers/createExtensions.js:61:10)
>     at handler (/home/boshra/projects/test/xen-orchestra/node_modules/now-and-later/lib/map.js:50:14)
>     at f (/home/boshra/projects/test/xen-orchestra/node_modules/once/once.js:25:25)
>     at f (/home/boshra/projects/test/xen-orchestra/node_modules/once/once.js:25:25)
>     at tryCatch (/home/boshra/projects/test/xen-orchestra/node_modules/async-done/index.js:24:15)
>     at done (/home/boshra/projects/test/xen-orchestra/node_modules/async-done/index.js:40:12)
> [15:01:34] 'build' errored after 5.43 s
> * xo-web:build − Error: 1
> ✖ 1
> error Command failed with exit code 1.

**Comment by Danp2** [comment]
Also posted @ https://github.com/vatesfr/xen-orchestra/issues/6497
