### ISSUE TITLE
Script doesn't run to completion

### ISSUE THREAD

**Issue by dpearceMN** [Jarli01/xenorchestra_installer#111]
**Describe the bug**
Tried this on Ubuntu Server 20 and 22. Ran the script but I see no open port on the VM's OS.

[messages.txt](https://github.com/Jarli01/xenorchestra_installer/files/9939029/messages.txt)

# systemctl start xo-server.service
Failed to start xo-server.service: Unit xo-server.service not found.

**Comment by Jarli01** [comment]
Please fill out the ticket template. .

**Comment by Danp2** [comment]
The script appears to be exiting prematurely following the `yarn build` command.

**Comment by Danp2** [comment]
In my limited testing the script works when run locally, but fails to proceed beyond the `yarn` commands when using `curl`.

**Comment by Danp2** [comment]
Retesting with 4GB based on this [forum feedback](https://xcp-ng.org/forum/topic/6523/fyi-applying-11-3-2022-and-11-4-2022-commits-in-xo-from-sources).

**Comment by dpearceMN** [comment]
> In my limited testing the script works when run locally, but fails to proceed beyond the `yarn` commands when using `curl`.

You are entirely correct. I downloaded the script and ran it in the terminal and it worked. Perhaps the documentation should change.

**Comment by Danp2** [comment]
The script is designed to run via curl so that the latest version of the script is always used. This worked correctly before, and I've no idea why it fails to complete now. Any ideas @Jarli01?

**Comment by Danp2** [comment]
The following method works correctly in my testing --

```
sudo bash
bash -c "$(curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh)"
```

**Comment by Danp2** [comment]
FYI, I updated the Readme file with the above commands.
