### ISSUE TITLE
Unit xo-server.service could not be found

### ISSUE THREAD

**Issue by pawael** [Jarli01/xenorchestra_installer#112]
Hey,
I tried to install XOA community edition and therefor I installed a fresh ubuntu 20.04 ltsr server, installed the xcp-ng guest tools, and updated the os. After that I worked through the guide from jarli. While installing I received some warnings but no erros. After the installation I tried to connect to the webgui but the site wasn't accessible. So I went through the troubleshooting guide and I checked the status of the service. So I checked the service first

systemctl status xo-server.service
gave me the error
Unit xo-server.service could not be found

I successfully deployed xoa 6 month ago using the same procedure but now I run in some trouble. Can someone help me please.
Please note that I'm not familiar with Linux and English is not my native language. If you need more information please let me know

node -v
v18.12.1

journalctl -u xo-server -f -n 50
the system hangs and no information provided

Thanks in advance
PaWäl

**Comment by Danp2** [comment]
This is a known issue. See #111 for details. Closing this as a duplicate.
