### ISSUE TITLE
XOCE Wrong Time in Stats

### ISSUE THREAD

**Issue by stevewest15** [Jarli01/xenorchestra_installer#115]
XOCE Stats shows the wrong time (about 3 hrs behind) what XOCE cli shows (see attached screenshot). Any recommendations on how to ensure XOCE web portal shows the same time as what XOCE server shows?
![2023-06-02_09-43-31](https://github.com/Jarli01/xenorchestra_installer/assets/13159246/56609f13-d274-41a6-8fcf-7512632ccd43)

**Comment by Danp2** [comment]
Have you checked the time on the XCP-ng server?

**Comment by stevewest15** [comment]
Hi Danp2,

Thank you for your assistance! The XCP-ng server has the correct time and timezone (see below):

[10:26 XCP25 ~]# date
Fri Jun  2 10:26:30 EDT 2023

[10:26 XCP25 ~]# timedatectl
      Local time: Fri 2023-06-02 10:26:36 EDT
  Universal time: Fri 2023-06-02 14:26:36 UTC
        RTC time: Fri 2023-06-02 14:26:36
       Time zone: America/New_York (EDT, -0400)
     NTP enabled: yes
NTP synchronized: yes
 RTC in local TZ: no
      DST active: yes
 Last DST change: DST began at
                  Sun 2023-03-12 01:59:59 EST
                  Sun 2023-03-12 03:00:00 EDT
 Next DST change: DST ends (the clock jumps one hour backwards) at
                  Sun 2023-11-05 01:59:59 EDT
                  Sun 2023-11-05 01:00:00 EST
[10:26 XCP25 ~]#

**Comment by Danp2** [comment]
IDK. I doubt that this is an issue caused by this script. Was the server ever configured with a different TZ?

**Comment by Danp2** [comment]
Seems like the time is adjusted to the local user's TZ. What TZ is configured on the local workstation?

**Comment by stevewest15** [comment]
Thank you! That was the issue. Much appreciate your assistance and continued support on XOCE.
