### ISSUE TITLE
Error plugin usage-report

### ISSUE THREAD

**Issue by jhonylanzza** [Jarli01/xenorchestra_installer#116]
Hello, after updating Xen Orchestra Community to the latest version, the usage-report plugin does not work and when I try to use the test plugin button, it generates the following message:

"Code: -32000

Message: Cannot convert undefined or null to object

{
  "message": "Cannot convert undefined or null to object",
  "name": "TypeError",
  "stack": "TypeError: Cannot convert undefined or null to object\n    at Function.entries (<anonymous>)\n    at getLastDays (/opt/xo/xo-builds/xen-orchestra-202305301025/packages/xo-server-usage-report/src/index.js:280:37)\n    at /opt/xo/xo-builds/xen-orchestra-202305301025/packages/xo-server-usage-report/src/index.js:320:42\n    at Generator.next (<anonymous>)\n    at asyncGeneratorStep (/opt/xo/xo-builds/xen-orchestra-202305301025/packages/xo-server-usage-report/src/index.js:24:41)\n    at _next (/opt/xo/xo-builds/xen-orchestra-202305301025/packages/xo-server-usage-report/src/index.js:24:41)\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at cb (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/util.js:355:42)\n    at tryCatcher (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/xo/xo-builds/xen-orchestra-202305301025/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (node:internal/timers:476:21)\n    at process.callbackTrampoline (node:internal/async_hooks:130:17)"
} "

xo-server version 5.115.0

xo-web version 5.118.0

Usage-report version (v0.10.4)

**Comment by Danp2** [comment]
It doesn't appear that you are using the latest sources, so first step would be to update and try again.

**Comment by jhonylanzza** [comment]
Hello,

I ran the update script, the cli is informed of the latest version, I believe, but when accessing the web application, it remains in a previous version, I already restarted the application, but it didn't solve it.

Version informed in the cli after the update: Updated version 5.116.3 / 5.119.1

Version informed in the web application: xo-server 5.115.0 / xo-web 5.118.0

**Comment by Danp2** [comment]
The version disparity may be due to the issue described [here](https://xcp-ng.org/forum/topic/6811/xen-orchestra-has-stopped-updating-commits).

Are you sure that you are in the correct repo? We don't use this directory structure -- `/opt/xo/xo-builds/xen-orchestra-202305301025/packages/xo-server-usage-report/src/index.js`

**Comment by jhonylanzza** [comment]
Could you tell me the correct procedure to perform a version update? Well, maybe I'm doing it incorrectly.

**Comment by Danp2** [comment]
@jhonylanzza The update is performed via a separate process that can be found [here](https://github.com/Jarli01/xenorchestra_updater). 

FWIW, I still suspect that you have stumbled into the wrong repo. Are you sure that you haven't been using [this one](https://github.com/ronivay/XenOrchestraInstallerUpdater) instead?

**Comment by jhonylanzza** [comment]
Hi Danp2. Yes, I was using the repository you indicated, but I was only able to solve my problem by downgrading the usage-report package to version 10.0, when I did that, the plugin started working again.

**Comment by Danp2** [comment]
Thanks for the update. I'm closing this issue since it doesn't involve this script. You may want to report your experience with `usage-report` to either the online forum or the appropriate GH repo.
