### ISSUE TITLE
Reverse Proxy Configuration

### ISSUE THREAD

**Issue by ltmike22** [Jarli01/xenorchestra_installer#117]
I have XO running from this script behind Nginx Proxy Manager. In the XO audit logs it's showing the IP of the proxy rather than the real IP of the user. NPM is passing the correct IP - does this script install allow any sort of "trusted proxy" config so it will show the real IP?

**Comment by Jarli01** [comment]
The installation script simply automates the installation of Xen Orchestra from Sources, you can install anything additional you need still.
