### ISSUE TITLE
Install script uses Node 20.9.0 and causes issues

### ISSUE THREAD

**Issue by dbdavidss** [Jarli01/xenorchestra_installer#119]
**Describe the bug**
Node version 20.9.0 causes Xen Orchestra to disconnect from host within a few seconds.

**To Reproduce**
Steps to reproduce the behavior:**
Use install script on a new Debian VM. Connect to the host.

**Expected behavior**
It should be able to connect to a new host without disconnecting after a few seconds.

**Screenshots**
N/A

**Desktop/Server details (please complete the following information):**
New XCP-NG 8.2.1
Install script with Node 20.9.0

**Additional context**
To fix, use the update script below with Node version 18.17.0 and it works as expected.
sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_updater/master/xo-update.sh | bash -s -- -n 18.17.0

**Comment by Danp2** [comment]
Thanks for the report. I'm aware of this issue, but I haven't taken to time to work out a proper fix. FWIW, you can simply enter the command `sudo n 18` to install the latest supported version of Node.

I suspect that XO will eventually work on Node LTS again at some point, so it's difficult to come up with a good fix for this issue that doesn't require constantly editing these scripts to maintain compatibility.

**Comment by Danp2** [comment]
Fixed in https://github.com/Jarli01/xenorchestra_installer/commit/d12423d78c0a45f00700852cc5ec3424bd5f903e
