### ISSUE TITLE
Not working with Debian 12

### ISSUE THREAD

**Issue by volkswagner** [Jarli01/xenorchestra_installer#120]
**Describe the bug**
XO connects to XCP-ng then becomes disconnected. It cycles, mostly disconnected but then for a moment
will show the server pool, then "unknown pool" then the pool field becomes empty.

**To Reproduce**
1. run script on fresh install of Debian 12
2. add server via web guie
3. watch web interface as pool appears then dissapears

**Expected behavior**
pool should remain connected

**Desktop/Server details (please complete the following information):**
 - OS: Debian 12
 - Browser all

**Comment by Danp2** [comment]
See #119 for existing open issue with temporary solution.
