### ISSUE TITLE
Warning on login

### ISSUE THREAD

**Issue by infodavide** [Jarli01/xenorchestra_installer#124]
Is it possible to remove or add a flag to remove the 'Warning on login' describing there is no support when using sources ?

**Comment by Danp2** [comment]
I doubt that we add this back into the script. You may want to review this [prior PR](https://github.com/Jarli01/xenorchestra_installer/pull/45) for some context.

**Comment by infodavide** [comment]
0k, I've seen the PR.

**Comment by Jarli01** [comment]
Yeah its not worthwhile to remove the banner, we did this a while back with a more permeant banner that the Vates team had implemented, and while we did remove it, it was just a headache. 

Plus the goal isn't to change the fundamental XO installation, but to make it super simple for the community to install XO without having to manually go through, [step by step of the documentation](https://xen-orchestra.com/docs/installation.html).
