### ISSUE TITLE
Settings-Log page in XO is empty

### ISSUE THREAD

**Issue by manilx** [Jarli01/xenorchestra_installer#125]
Installation went fine and all is running. The only thing I encounter is that I cannot check logs.
The respective page in Settings-Logs is empty.

Running another instance of XO using another script (https://github.com/ronivay/XenOrchestraInstallerUpdater) shows the logs just fine.

Pls advise

**Comment by Jarli01** [comment]
Please fill out the questions that is provided in the issue template so that we can help you.

**Comment by manilx** [comment]
Hi. When I follow the issue template link on https://github.com/Jarli01/xenorchestra_installer/blob/master/TROUBLESHOOTING.md#submitting-a-support-request I just get the page with "Add a title" and "Add a description", which I did. So please tell me what you want to know in addition.
Installed the script on Debian12....

**Comment by manilx** [comment]
> **Describe the bug** A clear and concise description of what the trouble is.
Installation went fine and all is running. The only thing I encounter is that I cannot check logs.
The respective page in Settings-Logs is empty.

Running another instance of XO using another script (https://github.com/ronivay/XenOrchestraInstallerUpdater) shows the logs just fine.
> **To Reproduce** Steps to reproduce the behavior:
Any error, which is encountered in XO and which generates the red error popup should be able to be checked under Settings-Logs.
When opening that page no logs are shown at all.

> **Desktop/Server details (please complete the following information):**
OS: Debian 12
Firefox
     * Browser [e.g. chrome, safari]
> **Confirm XOCE services are running** Please run `systemctl status xo-server.service` and paste the resulting output below.
> 
> **Provide the output of journalctl logs** Please run `journalctl -u xo-server -f -n 50` and paste the resulting output below.
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _objectsFetched: [Promise [Object]],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _eventWatchers: [Object: null prototype] {},
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _taskWatchers: [Object: null prototype],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _watchedTypes: undefined,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _callRetryWhenTooManyPendingTasks: [Object],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _maxUncoalescedVdis: 1,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _preferNbd: false,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _nbdOptions: undefined,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _syncHookSecret: undefined,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _syncHookTimeout: undefined,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _vdiDestroyRetryWhenInUse: [Object],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _genericWatchers: Set(0) {},
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _objectWatchers: [Object: null prototype] {},
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _guessVhdSizeOnImport: true,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _restartHostTimeout: 1200000,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _vmEvacuationConcurrency: 3,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       VDI_exportContent: [Function (anonymous)],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       VM_export: [Function (anonymous)],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _migrateVmWithStorageMotion: [Function (anonymous)],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       VM_snapshot: [Function (anonymous)],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       getObject: [Function (anonymous)],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _resolveDisconnected: [Function (anonymous)],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _types: [Array],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _lcToTypes: [Object: null prototype],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       xo: [Object],
Mar 27 13:56:39 XenOrchestra xo-server[506]:       _nTasks: 1,
Mar 27 13:56:39 XenOrchestra xo-server[506]:       [Symbol(kCapture)]: false
Mar 27 13:56:39 XenOrchestra xo-server[506]:     },
Mar 27 13:56:39 XenOrchestra xo-server[506]:     vmRef: 'OpaqueRef:9a4a034c-3c90-aeb5-c61a-b45f6f10039a',
Mar 27 13:56:39 XenOrchestra xo-server[506]:     compress: false,
Mar 27 13:56:39 XenOrchestra xo-server[506]:     format: 'xva'
Mar 27 13:56:39 XenOrchestra xo-server[506]:   },
Mar 27 13:56:39 XenOrchestra xo-server[506]:   error: TypeError: Cannot set properties of undefined (setting 'content-disposition')
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at Xo.handleExport (file:///opt/xen-orchestra/packages/xo-server/src/api/vm.mjs:1219:40),
Mar 27 13:56:39 XenOrchestra xo-server[506]:   fn: 'handleExport'
Mar 27 13:56:39 XenOrchestra xo-server[506]: }
Mar 27 13:56:39 XenOrchestra xo-server[506]: 2024-03-27T13:56:39.201Z xo:xo-server ERROR unhandled error event {
Mar 27 13:56:39 XenOrchestra xo-server[506]:   error: RequestAbortedError [AbortError]: Request aborted
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at BodyReadable.destroy (/opt/xen-orchestra/node_modules/undici/lib/api/readable.js:48:13)
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at ServerResponse.<anonymous> (file:///opt/xen-orchestra/packages/xo-server/src/api/vm.mjs:1217:32)
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at ServerResponse.emit (node:events:517:28)
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at ServerResponse.patchedEmit [as emit] (/opt/xen-orchestra/@xen-orchestra/log/configure.js:52:17)
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at emitCloseNT (node:_http_server:1020:10)
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at processTicksAndRejections (node:internal/process/task_queues:81:21)
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at runNextTicks (node:internal/process/task_queues:64:3)
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at processImmediate (node:internal/timers:447:9)
Mar 27 13:56:39 XenOrchestra xo-server[506]:       at process.callbackTrampoline (node:internal/async_hooks:128:17) {
Mar 27 13:56:39 XenOrchestra xo-server[506]:     code: 'UND_ERR_ABORTED'
Mar 27 13:56:39 XenOrchestra xo-server[506]:   }
Mar 27 13:56:39 XenOrchestra xo-server[506]: }

> 
> **Provide answers to these questions:**
> 
>     * Is this a fresh install or an upgrade?
Fresh install
> 
>     * Version of XOCE server and web interface you're running
Xen Orchestra, commit [88dd9] Master, commit [88dd9]

>     * What OS is XOCE running on?
Debian 12

>     * What method did you use to install XOCE (xo_install.sh, manual installation, etc)
install script: https://github.com/Jarli01/xenorchestra_installer/blob/master/xo_install.sh
> 
>     * Include what you've done so far in the installation, and if you got any error messages along the way.
> 
>     * Indicate whether or not you've manually edited any data directly.
Nothing done, just the script.

**Comment by manilx** [comment]
<img width="1363" alt="ScreenShot 2024-03-27 at 14 18 11" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/b00d995b-e5d3-4e81-9c73-006d3fdf3fb0">

**Comment by manilx** [comment]
Should be:

<img width="1347" alt="ScreenShot 2024-03-27 at 14 17 58" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/4981cbbb-7dbb-470b-ae92-5b61c750cdc1">

**Comment by Jarli01** [comment]
What build version is installed from ronivoy?

**Comment by manilx** [comment]
Latest from today.

--
Manfred Ell

**Comment by Jarli01** [comment]
So the XO from ronivoy's script is also running 88dd9?

**Comment by Jarli01** [comment]
The reason I'm asking this, is that this repo, installs the latest version provided from source, and makes no changes to the source. 

I can attempt the install myself to validate the issue you're experiencing, the solution would be provided from the source material, once an issue can be pinpointed.

**Comment by manilx** [comment]
Correct. Both are running the same builds.

**Comment by manilx** [comment]
<img width="1027" alt="ScreenShot 2024-03-27 at 14 32 07" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/4098b793-9731-461b-9c19-080f09bdc6e3">

**Comment by Jarli01** [comment]
Debian 12.5.1 correct?

**Comment by manilx** [comment]
<img width="514" alt="ScreenShot 2024-03-27 at 14 35 10" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/f2a3fbec-ddb3-449a-b620-1292bf56fa01">

**Comment by Jarli01** [comment]
I'm testing on my side and will report back. 

The most recent release that I see is "88dd987" so I'm not certain what is going on, let me validate and report back shortly.

**Comment by manilx** [comment]
Thx!

**Comment by manilx** [comment]
I just updated the ronivay XO and the other using your update script. Both now on 
<img width="1065" alt="ScreenShot 2024-03-27 at 14 38 50" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/ad8f6f2f-fdca-422a-8052-dbb5f8dd292a">

Issue remains

**Comment by manilx** [comment]
There were a few error messages on the update, don't know if normal:
<img width="1118" alt="ScreenShot 2024-03-27 at 14 41 34" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/8c0b9069-0657-47e4-bdab-ed624e8e10b4">

**Comment by Jarli01** [comment]
Warnings can be safely ignored, Errors would need attention.

**Comment by manilx** [comment]
As a test I just installed a fresh VM using Ubuntu Jammy Jellyfish 22.04.
Enabled root. Run your script. Imported settings. All OK.
But issue persists. So you can take the OS out of the equation.

**Comment by manilx** [comment]
Yes, only issue I have encountered.
The error I'm causing and which should show on the log (shows in ronivay) is trying to export a VM. Doesn't work in selfbuild XO. Works in XOA.
Wanted to report that in the forum but wanted to test your build first.
The error happens on both (so it is caused by build from sources) but here I encountered the issue I reported

**Comment by Jarli01** [comment]
Yeah there have been some issues with exporting recently from the source docs as well and its on the XO forums. I'm going to be stepping away shortly for a break, but should be able to validate if I encounter the same issue using debian bookworm 12.5.0 on my system here when I get back.

**Comment by Jarli01** [comment]
Interesting I was able to reproduce as well, though my version is now the latest. Still checking on it

**Comment by manilx** [comment]
Great and thx for checking  Something is broken… guess another bug they introduced. Seems to be frequent lately.

--
Manfred Ell

**Comment by manilx** [comment]
Just found another issue with this build: trying to export config doesn't do anything.

**Comment by Danp2** [comment]
FWIW, my VM doesn't have any issues with `Settings > Logs` or exporting a config file.

**Comment by manilx** [comment]
> FWIW, my VM doesn't have any issues with `Settings > Logs` or exporting a config file.

Any chance of sharing an export of it??

**Comment by Jarli01** [comment]
> FWIW, my VM doesn't have any issues with `Settings > Logs` or exporting a config file.

On a new build you had no issues? I encountered this twice myself (Debian and Ubuntu), I've not had a chance to follow up to source where the issue may be coming from.

**Comment by manilx** [comment]
Here I tried both fresh Debian12 and Ubuntu2204 and script.
Both had the issues described.

**Comment by Danp2** [comment]
> On a new build you had no issues?

No, it was my existing deployment updated to the latest sources.

> Any chance of sharing an export of it??

I don't see how that would be beneficial here.

**Comment by Jarli01** [comment]
Got it, on new deployments it appears that the Settings > Log page is simply not present as @manilx showed in his screenshot. I tested on both Debian and Ubuntu. 

Updating isn't impacted.

**Comment by RuKeBo** [comment]
I just happened to install this new on an Ubuntu 22.4 VM and I get a Settings > Log page.  I was having trouble updating my older version so I just made a fresh install.

**Comment by manilx** [comment]
Just tried it again now 
![Uploading ScreenShot 2024-03-28 at 18.08.00.png…]()
on Debian12 (I have a ready made template from a fresh install a couple of days ago I just have to clone and run the script): Issues remain. No config export and no logs.

Same test on Ubuntu 22.04 (fresh install from yesterday) template: same issues

**Comment by RuKeBo** [comment]
Out of date already.

![XO-About](https://github.com/Jarli01/xenorchestra_installer/assets/596065/075a759a-c3cc-4c65-a9ec-50d186de3c83)

**Comment by Danp2** [comment]
I just deployed a new VM and installed XO. The tab appears empty until it has something to display --
![image](https://github.com/Jarli01/xenorchestra_installer/assets/7101313/2a04198f-8c43-4d84-848b-e4379cdf625c)

**Comment by Jarli01** [comment]
> I just deployed a new VM and installed XO. The tab appears empty until it has something to display -- ![image](https://private-user-images.githubusercontent.com/7101313/317843140-2a04198f-8c43-4d84-848b-e4379cdf625c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE2NTE2MjgsIm5iZiI6MTcxMTY1MTMyOCwicGF0aCI6Ii83MTAxMzEzLzMxNzg0MzE0MC0yYTA0MTk4Zi04YzQzLTRkODQtODQ4Yi1lNDM3OWNkZjYyNWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjhUMTg0MjA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Y2U5ZmIzMzE1Yjg0NDVkNTQyZDA5ZmJkNmQ5ZTc3ZDdjNWJmZTBlNDhlMTNiZDVkZTUyYmMzNDlkYmViMzM1MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wdJ1obyRNaP9NWpgPTEqNBPwaeySXzi8bnWqZTSTIvQ)

That's definitely an improvement, before the Logs tab wouldn't even load, building a new one myself as a test.

**Comment by manilx** [comment]
> I just deployed a new VM and installed XO. The tab appears empty until it has something to display -- !

Can you give me a quick command to create a log?

**Comment by Danp2** [comment]
> That's definitely an improvement, before the Logs tab wouldn't even load, building a new one myself as a test.

Are you sure it wasn't working correctly before? I think it was, but there wasn't anything to display. 🤔 

> Can you give me a quick command to create a log? Deploying new install at the moment.

That tab pretty much only logs errors, so do something stupid like try to add an NFS SR by pointing it to your XCP server. 😆

**Comment by Jarli01** [comment]
> > That's definitely an improvement, before the Logs tab wouldn't even load, building a new one myself as a test.
> 
> Are you sure it wasn't working correctly before? I think it was, but there wasn't anything to display. 🤔
> 
> > Can you give me a quick command to create a log? Deploying new install at the moment.
> 
> That tab pretty much only logs errors, so do something stupid like try to add an NFS SR by pointing it to your XCP server. 😆

That is a fair point, I think the other issue that was brought up was (untested by myself) that he couldn't export the configuration. 

The interesting point that I noticed was that the Tab headers within Logs wasn't presented, which definitely feels odd.

**Comment by manilx** [comment]
Just created new Debian12 install. Did the dumb thing you suggested and I got the log entry :)
BUT the previous install from where I reported this issue definitely didn't log the errors because I had various (backups and stuff). 

But the issue with not being able to export config remains.

**Comment by Danp2** [comment]
@Jarli01 I don't know if that behavior is new or not since it's been forever since I've had an empty error log. 😆 

Config exports are working fine for me, so maybe PEBCAK? 😉 What happens when you attempt to export a config?

**Comment by manilx** [comment]
> @Jarli01 I don't know if that behavior is new or not since it's been forever since I've had an empty error log. 😆
> 
> @manilx Config exports are working fine for me, so maybe PEBCAK? 😉 What happens when you attempt to export a config?

Nothing happens at all after I acknowledge the export dialogue. No error no export.

**Comment by manilx** [comment]
I just run the update script and got this:
<img width="951" alt="ScreenShot 2024-03-28 at 19 09 16" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/b607b67a-dda5-4fe0-b284-4af41abcb231">

**Comment by manilx** [comment]
BUT the config exported!

**Comment by manilx** [comment]
What should I input for "root of the repo to migrate"

**Comment by Jarli01** [comment]
```/opt/xen-orchestra``` is where we install into, I've not seen that error before though

**Comment by manilx** [comment]
Got error: 
<img width="955" alt="ScreenShot 2024-03-28 at 19 22 21" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/bb158352-6698-4758-8d5c-151e735a1217">

Easier to redeploy I guess

**Comment by manilx** [comment]
Status quo: **redeployed**

Logs OK, Config export OK.
<img width="947" alt="ScreenShot 2024-03-28 at 19 29 50" src="https://github.com/Jarli01/xenorchestra_installer/assets/75693244/72483834-bfee-418c-8e42-f092501fa04d">

**Comment by Danp2** [comment]
No need to redeploy. Stop trying to update `turbo`... problem solved! 😆

**Comment by manilx** [comment]
> No need to redeploy. Stop trying to update `turbo`... problem solved! 😆

Yes but then error messages get me uneasy 😉  Especially if I can't understand them  😛

**Comment by Jarli01** [comment]
We don't have any means of making those error messages "user friendly" as they are from a different developer.

**Comment by manilx** [comment]
> We don't have any means of making those error messages "user friendly" as they are from a different developer.

Yes, I understand that! Perhaps just add description what to do in those cases on you update script page. Others might also stumble over that....

**Comment by manilx** [comment]
Last question to the exerts here: What deploy do you recommend (unbiased if possible ;) )
The ronivay one or this? I don't quite see the difference (apart from this one being similar/equal to the vates one on their docs).

**Comment by Jarli01** [comment]
This one was setup years ago to imitate the "source" documentation from vates' information, but to automatically complete the process for you. It'll give you a completely functional XO. 

Ronivoy's script attempts to do way more, outside of just getting you a working XO interface, which is that projects goal.

**Comment by Danp2** [comment]
> unbiased if possible 

🤣 

I would say that you should use which ever one works best for you.

**Comment by manilx** [comment]
> > unbiased if possible
> 
> 🤣
> 
> I would say that you should use which ever one works best for you.

Point taken ;)
