### ISSUE TITLE
Revise build process to pull from specific / latest "tagged" release

### ISSUE THREAD

**Issue by Danp2** [Jarli01/xenorchestra_installer#17]
#### Expected Behavior

-----
We should enhance the build process to allow the user to specify a tag to indicate the exact point in time to be used as the origin for the source pull. If one is not indicated, then use the most recent.

This should allow for VM creation from a better controlled environment.

#### Actual Behavior

-----
The current install and upgrade processes grab the latest source from the current branch (`master` unless the user has switched to a different one). The end result isn't necessarily as stable as if it were built from a specific release tag.

**Comment by Jarli01** [comment]
Are you thinking as a means to install from a different branch?

**Comment by Danp2** [comment]
No, strictly to control the exact source used in the build process. 

For example, The most recent release was on 4/19 with the tag "xo-server-usage-report-v0.4.2". The prior tag to that was xo-web-v5.18.3 on 4/17.

There have been 16 commits since the release on 4/17, so if you create a VM today from the latest source then you are technically running XO 5.18.3 plus these add'l commits. A VM build last Thursday would still show version 5.18.3 but would contain 3 less commits.

**Comment by Jarli01** [comment]
Running the updater would correct this though, but it wouldn't be to an exact tag.

**Comment by Danp2** [comment]
No, the updater has the same issue and would need to be updated as well.

**Comment by Jarli01** [comment]
OK I see what you're saying, I'm curious how we could do that.

**Comment by Danp2** [comment]
I looked into this a bit the other day. `git describe --abbrev=0 --tags` give the most recent tag name.

**Comment by Jarli01** [comment]
That's fine and all, but we would need a way to query GH for all tags, and then allow allow for input prior installation.

**Comment by Jarli01** [comment]
```git tag -l``` will list all available tags

**Comment by Danp2** [comment]
Not what I was thinking, but I guess you could allow the user to pick from a list (more complicated).

I envisioned that in most cases the user wouldn't supply a tag, so the script would grab the most recent tag.

**Comment by Jarli01** [comment]
Asking the user if they want to use the "most current" or a specific release is probably do-able, but I don't think it would be wise to leave it to anyone to type in themselves.

**Comment by Jarli01** [comment]
Some of the tag names get pretty crazy, if we could pull in a list and have the user select from the list that would likely be better.

**Comment by Jarli01** [comment]
@Danp2 is this something you wanted to try and sort out?

**Comment by Danp2** [comment]
Not at this time.
