### ISSUE TITLE
Adding the Plugins would be great

### ISSUE THREAD

**Issue by didebeach** [Jarli01/xenorchestra_installer#18]
#### Expected Behavior

The plugins should be installed (not activated) so that we can use it.

#### Actual Behavior

The plugins are empty

 
#### Provide answers to these questions:
- it's not installed after on a fresh installation 
- version 5.19.x
- debian 9.4
- installed with xo_install.sh

**Comment by Danp2** [comment]
Good idea. This is easy to implement now that all of the source is under a single repository

**Comment by didebeach** [comment]
Amazing,
I first had to delete the old installation but then it was working.  My first try to install it again was not succesffull.
May an idea is that you include it in the upgrade script as well? :-)
THANK YOU
