### ISSUE TITLE
plugins ? 

### ISSUE THREAD

**Issue by txsastre** [Jarli01/xenorchestra_installer#20]
once the XOCE is working preaty good.

how can I install / enable the plugins ? 

I think that they are in /opt/xen-orchestra/packages what should I do now ? 

thanks

**Comment by Jarli01** [comment]
You'd follow the process for [Plugins outlined here](https://xen-orchestra.com/docs/plugins.html).

**Comment by txsastre** [comment]
well solved
doing this 
ln -s /opt/xen-orchestra/packages/xo-server-load-balancer /opt/xen-orchestra/packages/xo-server/node_modules/

and then yarn && yarn build && service xo-server restart

adapted from this post https://xen-orchestra.com/forum/topic/605/can-t-install-plugins-in-xen-orchestra

should be possible to add this to the install script so the plugins where installed by default ?

**Comment by Jarli01** [comment]
There are many plugins installed by default from the gitgo. .

Are you saying you had no plugins listed under Settings > Plugins?

**Comment by txsastre** [comment]
exactly, in settings->Plugins I do not have anything.

well, right now I have load-balancer as I could install before.

**Comment by txsastre** [comment]
no, I don't have that.

now I have this, because I installed 2 as explained at the beginning.

![seleccio_003](https://user-images.githubusercontent.com/10468371/39924202-3110c9f2-5527-11e8-8c72-fc2ef47f93e8.png)

**Comment by Jarli01** [comment]
I'm testing now with my installation script.

**Comment by Danp2** [comment]
@txsastre When did you perform your initial install? The script was recently updated to automatically "install" the plugins, so I'm wondering if your install was performed before that enhancement.

**Comment by txsastre** [comment]
mmm... as far as I can remember when I used your script it installed the 5.18.3 version of XOCE and now its 5.19.3

**Comment by Jarli01** [comment]
I just confirmed, the script works as intended and installs the listed plugins I showed by default.

You must've created this VM more than 9 days ago (which is when these changes were committed).

**Comment by txsastre** [comment]
ah, oks, that's it, the VM is older than you say.
so, what should I do know, run the installation script again ?

**Comment by Jarli01** [comment]
Just export your config, save it to your system and then create a new installation. 

Only in cases where you are using SSL, hosting on vultr or some such service does it make XO indisposable and changes the concept of how the system was meant. 

If you are hosting locally (on your hypervisor), create a new VM and run the script to install and create a new XOCE and import your config. 

If you don't or can't do that than you'll want to manually install the plugins you need.

**Comment by Danp2** [comment]
We haven't gotten around to adding this to the update script. You could manually run the code from within a putty session --
```
for source in =$(ls -d /opt/xen-orchestra/packages/xo-server-*); do
    ln -s "$source" /usr/local/lib/node_modules/
done
```

**Comment by txsastre** [comment]
ok, right now is just a development VM, so I cant create a new one with no problem at all.

thank you for your script its very helpful :)

**Comment by Danp2** [comment]
Another option -- Just kill the /opt/xen-orchestra directory and then rerun the installation script.

**Comment by txsastre** [comment]
ok I answered the same time Danp2 was answering.
thanks you to Danp2.

nice tip, I will delete the directory and install again. As I said is a development / test VM so its not a problem to do that.

**Comment by txsastre** [comment]
by the way I did it and now I can see all of them.
nice work !
