### ISSUE TITLE
[Ubuntu 18.04 minimal] yarn can not be installed because of cmdtest

### ISSUE THREAD

**Issue by borzel** [Jarli01/xenorchestra_installer#24]
#### Expected Behavior

XOCE is installed and functional

-----

#### Actual Behavior

XOCE is not installed, but no error message in final output

-----

#### Problem
`yarn` can not be installed/used because the package `cmdtest` provides also binary called `yarn`
http://www.openmutual.org/2017/10/yarn-install-fails-as-it-is-using-cmdtest-package-and-not-yarn/

-----

#### Solution
remove package `cmdtest` so that yarn can be installed, maybe check at start if `cmdtest` is installed and display some error message

**Comment by Jarli01** [comment]
Can you provide a link to the ISO you've used?

**Comment by borzel** [comment]
Of course:
* http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso
* selected only `openssh server` to install on package selection

**Comment by Jarli01** [comment]
You also installed curl, as it's not included in this ISO by default.

**Comment by Jarli01** [comment]
Whatever this package is for, it seems to still be unstable, https://launchpad.net/ubuntu/+source/cmdtest

I'm not sure if us addressing it by checking for and removing it is ideal as this currently only affects the mini iso that is provided above. 

Simply removing the one package ```sudo apt remove cmdtest``` before running the installation script works without issue but could cause future issues if this package is pulled into the main server distro. 

@borzel have you tried with the normal server iso and see if the issue persists?

For what it's worth this appears to be an issue from last year at least as far as I can tell. https://github.com/yarnpkg/yarn/issues/3189

**Comment by Jarli01** [comment]
Also worth noting it appears that this package is set to be removed, so that adds more to the case of should it be something that needs to be addressed by us or the upstream team?

**Comment by borzel** [comment]
I did not try with the normal server iso. Use the mini.iso for years, so servers are small and light.

**Comment by Jarli01** [comment]
Hi Borzel, 

This isn't an issue we should be "fixing" the debian/ubuntu team appear to already know about this issue and have it planned to remove it. 

This particular issue isn't one that should be corrected by the installation script provided here. 

Please remove the package manually if you wish to use this particular ISO and then install as outlined in the above information. Alternatively please use a different ISO that doesn't contain this package.

**Comment by borzel** [comment]
Ok, thats fine :-)
