### ISSUE TITLE
Default username / password not working

### ISSUE THREAD

**Issue by pkropf** [Jarli01/xenorchestra_installer#36]
#### Expected Behavior

With a fresh install on Ubuntu 18.04 (also tried Debian 8) the supplied username / password do not work. The error is Invalid credentials.

-----

#### Actual Behavior

-----

#### Confirm XOCE services are running

```systemctl status xo-server.service```

	● xo-server.service - XO Server
	   Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
	   Active: active (running) since Wed 2018-09-19 18:04:47 UTC; 2min 2s ago
	 Main PID: 11754 (node)
		Tasks: 16 (limit: 4624)
	   CGroup: /system.slice/xo-server.service
			   ├─11754 /usr/local/bin/node ./bin/xo-server
			   └─11786 /usr/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/child.js

	Sep 19 18:04:54 xo xo-server[11754]: xo-server-cloud: next attempt in 1010 ms
	Sep 19 18:04:55 xo xo-server[11754]: xo-server-cloud: next attempt in 960 ms
	Sep 19 18:04:56 xo xo-server[11754]: xo-server-cloud: next attempt in 1918 ms
	Sep 19 18:04:58 xo xo-server[11754]: xo-server-cloud: next attempt in 2953 ms
	Sep 19 18:05:01 xo xo-server[11754]: xo-server-cloud: next attempt in 4995 ms
	Sep 19 18:05:06 xo xo-server[11754]: xo-server-cloud: next attempt in 7927 ms
	Sep 19 18:05:14 xo xo-server[11754]: xo-server-cloud: next attempt in 13227 ms
	Sep 19 18:05:27 xo xo-server[11754]: xo-server-cloud: next attempt in 20034 ms
	Sep 19 18:05:47 xo xo-server[11754]: xo-server-cloud: next attempt in 35536 ms
	Sep 19 18:06:22 xo xo-server[11754]: xo-server-cloud: next attempt in 52324 ms

	#### Provide the output of journalctl logs

	```journalctl -u xo-server -f -n 50```
	-- Logs begin at Wed 2018-09-19 13:05:44 UTC. --
	Sep 19 18:04:53 xo xo-server[11754]: 2018-09-19T18:04:53.281Z xo:plugin register load-balancer
	Sep 19 18:04:53 xo xo-server[11754]: 2018-09-19T18:04:53.301Z xo:plugin register perf-alert
	Sep 19 18:04:53 xo xo-server[11754]: 2018-09-19T18:04:53.321Z xo:plugin register test-plugin
	Sep 19 18:04:53 xo xo-server[11754]: 2018-09-19T18:04:53.324Z xo:plugin register transport-email
	Sep 19 18:04:53 xo xo-server[11754]: 2018-09-19T18:04:53.440Z xo:plugin register transport-nagios
	Sep 19 18:04:53 xo xo-server[11754]: 2018-09-19T18:04:53.445Z xo:plugin register transport-slack
	Sep 19 18:04:53 xo xo-server[11754]: 2018-09-19T18:04:53.667Z xo:plugin register transport-xmpp
	Sep 19 18:04:53 xo xo-server[11754]: 2018-09-19T18:04:53.756Z xo:plugin register usage-report
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.050Z xo:plugin failed register auth-github
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.052Z xo:plugin Error: Cannot find module '/usr/local/lib/node_modules//xo-server-auth-github'
	Sep 19 18:04:54 xo xo-server[11754]:     at require (internal/module.js:11:18)
	Sep 19 18:04:54 xo xo-server[11754]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
	Sep 19 18:04:54 xo xo-server[11754]:     at process._tickCallback (internal/process/next_tick.js:181:9)
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.053Z xo:perf blocked for 1255ms
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin auth-google for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin auth-ldap for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin auth-saml for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin backup-reports for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin cloud for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin load-balancer for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin perf-alert for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin test-plugin for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin transport-email for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin transport-nagios for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin transport-slack for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin transport-xmpp for the first time
	Sep 19 18:04:54 xo xo-server[11754]: [NOTICE] register plugin usage-report for the first time
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.095Z xo:plugin successfully register auth-google
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.096Z xo:plugin successfully register auth-ldap
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.096Z xo:plugin successfully register auth-saml
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.097Z xo:plugin successfully register backup-reports
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.097Z xo:plugin successfully register load-balancer
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.098Z xo:plugin successfully register perf-alert
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.098Z xo:plugin successfully register test-plugin
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.098Z xo:plugin successfully register transport-email
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.099Z xo:plugin successfully register transport-nagios
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.099Z xo:plugin successfully register transport-slack
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.100Z xo:plugin successfully register transport-xmpp
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.100Z xo:plugin successfully register usage-report
	Sep 19 18:04:54 xo xo-server[11754]: 2018-09-19T18:04:54.101Z xo:plugin successfully register cloud
	Sep 19 18:04:54 xo xo-server[11754]: xo-server-cloud: next attempt in 1010 ms
	Sep 19 18:04:55 xo xo-server[11754]: xo-server-cloud: next attempt in 960 ms
	Sep 19 18:04:56 xo xo-server[11754]: xo-server-cloud: next attempt in 1918 ms
	Sep 19 18:04:58 xo xo-server[11754]: xo-server-cloud: next attempt in 2953 ms
	Sep 19 18:05:01 xo xo-server[11754]: xo-server-cloud: next attempt in 4995 ms
	Sep 19 18:05:06 xo xo-server[11754]: xo-server-cloud: next attempt in 7927 ms
	Sep 19 18:05:14 xo xo-server[11754]: xo-server-cloud: next attempt in 13227 ms
	Sep 19 18:05:27 xo xo-server[11754]: xo-server-cloud: next attempt in 20034 ms
	Sep 19 18:05:47 xo xo-server[11754]: xo-server-cloud: next attempt in 35536 ms
	Sep 19 18:06:22 xo xo-server[11754]: xo-server-cloud: next attempt in 52324 ms
	Sep 19 18:07:15 xo xo-server[11754]: xo-server-cloud: fail to connect to updater ConnectionError: connect ECONNREFUSED 127.0.0.1:9001
	Sep 19 18:07:15 xo xo-server[11754]:     at /opt/xen-orchestra/node_modules/jsonrpc-websocket-client/src/websocket-client.js:193:16
	Sep 19 18:07:15 xo xo-server[11754]:     at run (/opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:75:22)
	Sep 19 18:07:15 xo xo-server[11754]:     at /opt/xen-orchestra/node_modules/core-js/modules/es6.promise.js:92:30
	Sep 19 18:07:15 xo xo-server[11754]:     at flush (/opt/xen-orchestra/node_modules/core-js/modules/_microtask.js:18:9)
	Sep 19 18:07:15 xo xo-server[11754]:     at _combinedTickCallback (internal/process/next_tick.js:132:7)
	Sep 19 18:07:15 xo xo-server[11754]:     at process._tickCallback (internal/process/next_tick.js:181:9)
	Sep 19 18:07:15 xo xo-server[11754]: xo-server-cloud: next attempt in 992 ms
	Sep 19 18:07:16 xo xo-server[11754]: xo-server-cloud: next attempt in 1016 ms
	Sep 19 18:07:17 xo xo-server[11754]: xo-server-cloud: next attempt in 2012 ms
	Sep 19 18:07:19 xo xo-server[11754]: xo-server-cloud: next attempt in 3096 ms

 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  
Fresh install

- Version of XOCE server and web interface you're running? 
Latest

- What OS is XOCE running on? 
Ubuntu 18.04.1

- What method you used to install XOCE (xo_install.sh, manual installation, etc) 
xo_install.sh

- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error? 
Login page

- If a stacktrace is provided in the error, include that too. 
N/A

- Any errors that appear in your browser's error console. 
Invalid credentials

- Include what you've done so far in the installation, and if you got any error messages along the way. 
Ran xo_install.sh as root

- Indicate whether or not you've manually edited any data directly. 
No editing has been done.

**Comment by Danp2** [comment]
Issue has been reported to XO developers

https://github.com/vatesfr/xen-orchestra/issues/3431

**Comment by Jarli01** [comment]
@pkropf to not leave you hanging with an answer. This is already a known issue that is being investigated @Danp2 linked to the case with the development team. 

Since this is a new installation and you're having the issue, please be patient while the XOA development team works to find and fix the issue.

**Comment by Danp2** [comment]
@pkropf You can try the following to restore your machine to an earlier version of the source --

```
sudo bash
git checkout 0ad6c073ee1538887e13ebec7d3420fcace4d86e
yarn; yarn build
systemctl restart xo-server.service
```

**Comment by Jarli01** [comment]
@Danp2 this doesn't work from a clean install (at least not in my test here).

**Comment by pkropf** [comment]
That works! Thanks. I'll keep an eye out for fixes from the dev team and update once they're done.

**Comment by Danp2** [comment]
This issue has been resolved
