### ISSUE TITLE
Failed clean install 

### ISSUE THREAD

**Issue by astrugatch** [Jarli01/xenorchestra_installer#41]
#### Expected Behavior

Successfull Install

-----

#### Actual Behavior

Error during Yarn install:

	error https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "Unexpected end of data"
	info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
	yarn run v1.12.3
	$ scripts/run-script --parallel build
	module.js:550
		throw err;
		^

	Error: Cannot find module 'promise-toolbox'
		at Function.Module._resolveFilename (module.js:548:15)
		at Function.Module._load (module.js:475:25)
		at Module.require (module.js:597:17)
		at require (internal/module.js:11:18)
		at Object.<anonymous> (/opt/xen-orchestra/scripts/run-script:4:32)
		at Module._compile (module.js:653:30)
		at Object.Module._extensions..js (module.js:664:10)
		at Module.load (module.js:566:32)
		at tryModuleLoad (module.js:506:12)
		at Function.Module._load (module.js:498:3)
	error Command failed with exit code 1.
	info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
	Created symlink /etc/systemd/system/multi-user.target.wants/xo-server.service → /lib/systemd/system/xo-server.service.
	-----

#### Confirm XOCE services are running

Never completed install

#### Provide the output of journalctl logs

```journalctl -u xo-server -f -n 50```
 
	-- Logs begin at Thu 2018-11-15 13:45:44 EST. --
	Nov 15 13:54:34 XOA-deb systemd[1]: Started XO Server.
	Nov 15 13:54:34 XOA-deb xo-server[10960]: module.js:550
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     throw err;
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     ^
	Nov 15 13:54:34 XOA-deb xo-server[10960]: Error: Cannot find module 'bluebird'
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Function.Module._resolveFilename (module.js:548:15)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Function.Module._load (module.js:475:25)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Module.require (module.js:597:17)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at require (internal/module.js:11:18)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/bin/xo-server:12:18)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Module._compile (module.js:653:30)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Object.Module._extensions..js (module.js:664:10)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Module.load (module.js:566:32)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at tryModuleLoad (module.js:506:12)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Function.Module._load (module.js:498:3)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at Function.Module.runMain (module.js:694:10)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at startup (bootstrap_node.js:204:16)
	Nov 15 13:54:34 XOA-deb xo-server[10960]:     at bootstrap_node.js:625:3
	Nov 15 13:54:34 XOA-deb systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
	Nov 15 13:54:34 XOA-deb systemd[1]: xo-server.service: Unit entered failed state.
	Nov 15 13:54:34 XOA-deb systemd[1]: xo-server.service: Failed with result 'exit-code'.
	Nov 15 13:54:34 XOA-deb systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
	Nov 15 13:54:34 XOA-deb systemd[1]: Stopped XO Server.
	Nov 15 13:54:34 XOA-deb systemd[1]: Started XO Server.
	Nov 15 13:54:34 XOA-deb xo-server[10967]: module.js:550
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     throw err;
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     ^
	Nov 15 13:54:34 XOA-deb xo-server[10967]: Error: Cannot find module 'bluebird'
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Function.Module._resolveFilename (module.js:548:15)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Function.Module._load (module.js:475:25)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Module.require (module.js:597:17)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at require (internal/module.js:11:18)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/bin/xo-server:12:18)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Module._compile (module.js:653:30)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Object.Module._extensions..js (module.js:664:10)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Module.load (module.js:566:32)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at tryModuleLoad (module.js:506:12)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Function.Module._load (module.js:498:3)
	Nov 15 13:54:34 XOA-deb xo-server[10967]:     at Function.Module.runMain (module.js:694:10)

#### Provide answers to these questions:

- Is this a fresh install or an upgrade? Clean install, tried on both Debian 9 and Ubuntu 18.01
- Version of XOCE server and web interface you're running - NA
- What OS is XOCE running on? - tried on both Debian 9 and Ubuntu 18.01
- What method you used to install XOCE (xo_install.sh, manual installation, etc) xo_install.sh
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error NA
- If a stacktrace is provided in the error, include that too. NA
- Any errors that appear in your browser's error console. NA
- Include what you've done so far in the installation, and if you got any error messages along the way. NA
- Indicate whether or not you've manually edited any data directly. NA

**Comment by Danp2** [comment]
This is the same error that we were examining yesterday here -- https://github.com/Jarli01/xenorchestra_installer/issues/40

> Error during Yarn install:

Technically, at this stage of the script, the yarn package is already installed and yarn is being called to install all project dependencies.

**Comment by Danp2** [comment]
Still can't reproduce this. I wonder if it's due to a corrupt file that only certain people will see due to locale.

Try issuing the following from the command line and show us the console output --
```
sudo bash
cd /opt/xen-orchestra
yarn
```

**Comment by Jarli01** [comment]
So this file is no longer at the reported website, yesterday it was there. . .  for certain (I have it in my downloads). 

https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz

![chrome_2018-11-15_16-18-09](https://user-images.githubusercontent.com/14837699/48582278-0fd2c100-e8f2-11e8-9e16-fbf9d1b87f2f.png)

@Danp2 I haven't tested this (yet) but can you see where/what file your install pulled? 5.1.3 maybe?

**Comment by Jarli01** [comment]
So it is now 5.1.3 (dumb luck I just tried it and 5.1.3 immediately downloaded. 

https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.3.tgz

**Comment by Danp2** [comment]
@Jarli01 

> https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz

This link works just fine for me.

**Comment by Danp2** [comment]
Here's what is installed on my test system --

```
# yarn list | grep 'har-validator'
├─ har-validator@5.1.3
│  ├─ har-validator@~5.1.0
│  ├─ har-validator@5.1.2
```

**Comment by Jarli01** [comment]
> @Jarli01
> 
> > https://registry.yarnpkg.com/har-validator/-/har-validator-5.1.2.tgz
> 
> This link works just fine for me.

Interesting, I'm getting that error in the picture I posted. Going to see if I can install and what version of the validator I get.

**Comment by Jarli01** [comment]
I just got the same error with the har-validator. 

This looks like a platform issue since where this file is coming from, is saying the file isn't found.

**Comment by Jarli01** [comment]
Since this appears to be an issue with a dependency there isn't much that we can do. You could attempt a manual installation following the source directions but I suspect the same issue with occur. 

Or you may get lucky and get this validator file. 

Thanks for being patient.

**Comment by Jarli01** [comment]
I'll have to check what version npm is using for the har-validator.

Since the upstream Dev has removed this version it's obvious that we can't continue to use the npm version. 

Which also means the XO team should also be forced to update off of v8..

**Comment by Jarli01** [comment]
Since the dependencies have been updated, this issue appears resolved. Please try the installation again and let us know if you continue to have issues.
