### ISSUE TITLE
Ubuntu Disco (19.04) fails with node issues 

### ISSUE THREAD

**Issue by Jarli01** [Jarli01/xenorchestra_installer#46]
#### Expected Behavior

A complete installation without issue.

-----

#### Actual Behavior

Build process fails, apparently due to node based on the log. 	

	## Confirming "disco" is supported...

	+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/disco/Release'

	## Adding the NodeSource signing key to your keyring...

	+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
	OK

	## Creating apt sources list file for the NodeSource Node.js 8.x LTS Carbon repo...

	+ echo 'deb https://deb.nodesource.com/node_8.x disco main' > /etc/apt/sources.list.d/nodesource.list
	+ echo 'deb-src https://deb.nodesource.com/node_8.x disco main' >> /etc/apt/sources.list.d/nodesource.list

	## Running `apt-get update` for you...

	+ apt-get update
 
Where as on 18.04

	## Confirming "bionic" is supported...

	+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/bionic/Release'

	## Adding the NodeSource signing key to your keyring...

	+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
	OK

	## Creating apt sources list file for the NodeSource Node.js 8.x LTS Carbon repo...

	+ echo 'deb https://deb.nodesource.com/node_8.x bionic main' > /etc/apt/sources.list.d/nodesource.list
	+ echo 'deb-src https://deb.nodesource.com/node_8.x bionic main' >> /etc/apt/sources.list.d/nodesource.list

	## Running `apt-get update` for you...

	+ apt-get update

**Comment by Jarli01** [comment]
![VirtualBoxVM_uVjbg8UPDl](https://user-images.githubusercontent.com/14837699/57040966-fbc81500-6c2e-11e9-9335-e1dfb8d895e6.png)

**Comment by Jarli01** [comment]
With the correct version of node manually installed the service continues to reboot over and over again. 

	May 03 12:58:38 xoce xo-server[16303]: 2019-05-03T12:58:38.793Z - xo:xo-server - [ERROR] uncaught exception
	May 03 12:58:38 xoce xo-server[16303]: { error:
	May 03 12:58:38 xoce xo-server[16303]:    { Error: Could not locate the bindings file. Tried:
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/build/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/build/Debug/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/build/Release/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/out/Debug/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/Debug/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/out/Release/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/Release/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/build/default/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:     → /opt/xen-orchestra/packages/xo-server/compiled/10.15.2/linux/x64/leveldown.node
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.require (internal/modules/cjs/loader.js:637:17)
	May 03 12:58:38 xoce xo-server[16303]:        at require (internal/modules/cjs/helpers.js:22:18)
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.require (internal/modules/cjs/loader.js:637:17)
	May 03 12:58:38 xoce xo-server[16303]:        at require (internal/modules/cjs/helpers.js:22:18)
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.require (internal/modules/cjs/loader.js:637:17)
	May 03 12:58:38 xoce xo-server[16303]:        at require (internal/modules/cjs/helpers.js:22:18)
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.require (internal/modules/cjs/loader.js:637:17)
	May 03 12:58:38 xoce xo-server[16303]:        at require (internal/modules/cjs/helpers.js:22:18)
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.require (internal/modules/cjs/loader.js:637:17)
	May 03 12:58:38 xoce xo-server[16303]:        at require (internal/modules/cjs/helpers.js:22:18)
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.require (internal/modules/cjs/loader.js:637:17)
	May 03 12:58:38 xoce xo-server[16303]:        at require (internal/modules/cjs/helpers.js:22:18)
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.require (internal/modules/cjs/loader.js:637:17)
	May 03 12:58:38 xoce xo-server[16303]:        at require (internal/modules/cjs/helpers.js:22:18)
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.require (internal/modules/cjs/loader.js:637:17)
	May 03 12:58:38 xoce xo-server[16303]:        at require (internal/modules/cjs/helpers.js:22:18)
	May 03 12:58:38 xoce xo-server[16303]:        at Module._compile (internal/modules/cjs/loader.js:689:30)
	May 03 12:58:38 xoce xo-server[16303]:        at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
	May 03 12:58:38 xoce xo-server[16303]:        at Module.load (internal/modules/cjs/loader.js:599:32)
	May 03 12:58:38 xoce xo-server[16303]:        at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module._load (internal/modules/cjs/loader.js:530:3)
	May 03 12:58:38 xoce xo-server[16303]:        at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
	May 03 12:58:38 xoce xo-server[16303]:        at startup (internal/bootstrap/node.js:283:19)
	May 03 12:58:38 xoce xo-server[16303]:        at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3)
	May 03 12:58:38 xoce xo-server[16303]:      tries:
	May 03 12:58:38 xoce xo-server[16303]:       [ '/opt/xen-orchestra/packages/xo-server/build/leveldown.node',
	May 03 12:58:38 xoce xo-server[16303]:         '/opt/xen-orchestra/packages/xo-server/build/Debug/leveldown.node',
	May 03 12:58:38 xoce xo-server[16303]:         '/opt/xen-orchestra/packages/xo-server/build/Release/leveldown.node',
	May 03 12:58:38 xoce xo-server[16303]:         '/opt/xen-orchestra/packages/xo-server/out/Debug/leveldown.node',
	May 03 12:58:38 xoce xo-server[16303]:         '/opt/xen-orchestra/packages/xo-server/Debug/leveldown.node',
	May 03 12:58:38 xoce xo-server[16303]:         '/opt/xen-orchestra/packages/xo-server/out/Release/leveldown.node',
	May 03 12:58:38 xoce xo-server[16303]:         '/opt/xen-orchestra/packages/xo-server/Release/leveldown.node',
	May 03 12:58:38 xoce xo-server[16303]:         '/opt/xen-orchestra/packages/xo-server/build/default/leveldown.node',
	May 03 12:58:38 xoce xo-server[16303]:         '/opt/xen-orchestra/packages/xo-server/compiled/10.15.2/linux/x64/leveldown.node' ] } }
	May 03 12:58:38 xoce systemd[1]: xo-server.service: Succeeded.
	May 03 12:58:39 xoce systemd[1]: xo-server.service: Service RestartSec=100ms expired, scheduling restart.
	May 03 12:58:39 xoce systemd[1]: xo-server.service: Scheduled restart job, restart counter is at 317.
	May 03 12:58:39 xoce systemd[1]: Stopped XO Server.
	May 03 12:58:39 xoce systemd[1]: Started XO Server.

**Comment by Danp2** [comment]
This appears to be an issue with the service established by this install script. Haven't had a chance to look into it further, but `yarn start` from the /opt/xen-orchestra/packages/xo-server directory works as expected.

**Comment by Danp2** [comment]
Please test this mod --

`sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/dp_node8fix/xo_install.sh | bash`

**Comment by Jarli01** [comment]
testing now

**Comment by Danp2** [comment]
This works successfully for me on Ubuntu 19.04. I don't have time to test the others, but I don't believe this change should affect other distros

**Comment by Jarli01** [comment]
That worked for me as well on 19.04.
