### ISSUE TITLE
Change locale and English verbiage - No Support

### ISSUE THREAD

**Issue by Jarli01** [Jarli01/xenorchestra_installer#49]
So on an installation I have here, there are reoccurring instances of things saying "No Support" and while this can be considered accurate from the vatesfr team, even they do offer support for built from sources installations - albeit without any priority. 

This is to discuss changing the verbiage of "No Support" on the navigation bar an in different locales to something more communal. Maybe something like "Community Support". 

The files that would need to be adjusted can be found in ``/opt/xen-orchestra/packages/xo-web/src/common/intl`` and ``/opt/xen-orchestra/packages/xo-web/src/common/intl/locales``

Specifically messages.js and then the individual locales files under the locales directory.

**Comment by Danp2** [comment]
It may be wishful thinking, but I'd like to think that we could submit a PR to the main GH repo so that we aren't working against the efforts of the primary development team.

**Comment by Jarli01** [comment]
I'm not sure how that would address the underlying vibe that has existed since this script began. I'm happy to discuss ways in which we might be able to do this, but just like with the ability to not restore a config file. 

That's weird, and to make it work a config change was required

**Comment by FoxieHazmat** [comment]
So it looks like this is the second change needed to the core of xoce? I think that vatesfr should work with these scripting repos to make it easier to manage the changes. If they want to see a decrease in people reaching out to them, decrease the potential issues scripters have to deal.

Perhaps a config file where we could punch in the repo url that would change every support link would be a great start.

**Comment by Jarli01** [comment]
So the change isn't to the core of what is XO, just to verbiage within the source files in an attempt to make the language not so off putting and more clear that community support is the only option, and that paid support is not an option if installing from source. 

We could make these changes during the install using the script, like I have a PR for or we could submit a PR to the vates team and see if they'd incorporate the changes there.

**Comment by FoxieHazmat** [comment]
Switching from no support to community support in this repo first would be my preference. 

If scripts cause a majority of the issues as they claim, with this being one of the major ones, both this and the xoce repos should see that shift in support requests. That would be good evidence to present for source adoption.

We can at least start by doing our part.

**Comment by Jarli01** [comment]
While I agree that changing some of the verbiage here via this install script would at least be a means of evidence, the goal isn't to prove or disprove what the vatesfr team is stating but to hopefully get people to understand where and what level of support is had with "building from source."

It's a bit of a battle, because and I feel very strong that at least Olivier doesn't want to support at all the source installation method and as such should simply instruct his team to not offer support if someone doesn't have a contract with them. 

So while making these changes makes sense from a community standpoint, the problem lies with the Vatesfr business and not the software or verbiage as it exists and is portrayed.

**Comment by FoxieHazmat** [comment]
I don't want to prove or disprove; best case is it takes a noticeable load off of their dev team which could inspire them to at least acknowledge that the scripts' are able to handle their own support.

So I changed 'No support' to 'Community support' and I don't like it. Its too many characters so it expands the entire bar to fit. What about 'Community help' or even just 'Community'?

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/34377501/57155229-e971e680-6da8-11e9-921c-e6755e3f3a59.png">

**Comment by FoxieHazmat** [comment]
Just throwing out ideas... 

<img width="1679" alt="image" src="https://user-images.githubusercontent.com/34377501/57158302-1d510a00-6db1-11e9-94cd-d587ff12ddd7.png">

**Comment by Jarli01** [comment]
Thumbs up for the "If you are having issues pretty please here for support information and the link to submit a bug report! Thank you." 

**_Cause that's what we're going with!!_**

**Comment by Jarli01** [comment]
It looks as though the upstream team is making some [meaningful verbiage changes](https://github.com/vatesfr/xen-orchestra/pull/4186#event-2320270475) as well. 

Which hopefully will help to address the issues.

**Comment by Danp2** [comment]
How about adding the word Pro, so the end result is `No Pro support`?

**Comment by Jarli01** [comment]
I thought about that change, and while it initially is correct, it may not always be accurate as the VatesFR team may still offer support. 

Maybe something less pay/no-pay would be better? 

Like "Limited" or just something even less specific like "Open Edition"

**Comment by Jarli01** [comment]
![chrome_DQc8g97aMe](https://user-images.githubusercontent.com/14837699/57713634-dc72b400-7640-11e9-8f92-1c17c65e4c02.png)

What do you think?

**Comment by Jarli01** [comment]
![chrome_iTKe18q4Gt](https://user-images.githubusercontent.com/14837699/57714221-0d9fb400-7642-11e9-921a-497d8840460c.png)

**Comment by Jarli01** [comment]
![IPrMbkhW2Z](https://user-images.githubusercontent.com/14837699/57714711-1775e700-7643-11e9-97a9-fc2d014986cb.png)

This change is made by editing /opt/xen-orchestra/packages/xo-web/src/xo-app/about/index.js line #84

**Comment by Danp2** [comment]
What about just hiding this element, since it takes you to the About page anyways/

**Comment by Jarli01** [comment]
I'd honestly think leaving it there makes the most sense compared to just outright hiding/removing it.

**Comment by Jarli01** [comment]
@Danp2 why do you think hiding makes sense? I mean, sure we could, but I'm actively attempting to get @olivierlambert to make upstream changes, that would make driving people to the correct source of support more beneficial. 

Unless he's going to continue being a prick about every change that he believes to be perfect.

**Comment by Jarli01** [comment]
One thing that might be worth hiding or at least changing the verbiage throughout is the XOSAN page, as that's just ugly as all sin. 

The broken English alone is bad enough. . . 

![chrome_JjQDotSNKi](https://user-images.githubusercontent.com/14837699/57722226-fa95df80-7653-11e9-99d1-035e3f684b41.png)

**Comment by Jarli01** [comment]
Since we are on the topic of adding declarations to the Readme and updating URLs I think we should push this change through so as to close this loop and highlight where support is to be requested first. 

@Danp2 @stormi @FoxieHazmat  any feedback?
