### ISSUE TITLE
New install won't start

### ISSUE THREAD

**Issue by GoodComputerGuy** [Jarli01/xenorchestra_installer#52]
#### Expected Behavior

Server starts.

-----

#### Actual Behavior

Service isn't running.

-----

#### Confirm XOCE services are running

```systemctl status xo-server.service```
● xo-server.service - XO Server
   Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2019-05-23 14:52:17 EDT; 52min ago
  Process: 1036 ExecStart=/usr/local/bin/node ./bin/xo-server (code=exited, status=1/FAILURE)
 Main PID: 1036 (code=exited, status=1/FAILURE)

May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILUR
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Unit entered failed state.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
May 23 14:52:17 xenorchestra systemd[1]: Stopped XO Server.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Start request repeated too quickly.
May 23 14:52:17 xenorchestra systemd[1]: Failed to start XO Server.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Unit entered failed state.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Failed with result 'exit-code'.

#### Provide the output of journalctl logs

```journalctl -u xo-server -f -n 50```
 
-- Logs begin at Thu 2019-05-23 14:41:28 EDT. --
May 23 14:52:16 xenorchestra systemd[1]: Started XO Server.
May 23 14:52:17 xenorchestra xo-server[1029]: module.js:550
May 23 14:52:17 xenorchestra xo-server[1029]:     throw err;
May 23 14:52:17 xenorchestra xo-server[1029]:     ^
May 23 14:52:17 xenorchestra xo-server[1029]: Error: Cannot find module 'bluebird'
May 23 14:52:17 xenorchestra xo-server[1029]:     at Function.Module._resolveFilename (module.js:548:15)
May 23 14:52:17 xenorchestra xo-server[1029]:     at Function.Module._load (module.js:475:25)
May 23 14:52:17 xenorchestra xo-server[1029]:     at Module.require (module.js:597:17)
May 23 14:52:17 xenorchestra xo-server[1029]:     at require (internal/module.js:11:18)
May 23 14:52:17 xenorchestra xo-server[1029]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/bin/xo-server:17:18)
May 23 14:52:17 xenorchestra xo-server[1029]:     at Module._compile (module.js:653:30)
May 23 14:52:17 xenorchestra xo-server[1029]:     at Object.Module._extensions..js (module.js:664:10)
May 23 14:52:17 xenorchestra xo-server[1029]:     at Module.load (module.js:566:32)
May 23 14:52:17 xenorchestra xo-server[1029]:     at tryModuleLoad (module.js:506:12)
May 23 14:52:17 xenorchestra xo-server[1029]:     at Function.Module._load (module.js:498:3)
May 23 14:52:17 xenorchestra xo-server[1029]:     at Function.Module.runMain (module.js:694:10)
May 23 14:52:17 xenorchestra xo-server[1029]:     at startup (bootstrap_node.js:204:16)
May 23 14:52:17 xenorchestra xo-server[1029]:     at bootstrap_node.js:625:3
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Unit entered failed state.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
May 23 14:52:17 xenorchestra systemd[1]: Stopped XO Server.
May 23 14:52:17 xenorchestra systemd[1]: Started XO Server.
May 23 14:52:17 xenorchestra xo-server[1036]: module.js:550
May 23 14:52:17 xenorchestra xo-server[1036]:     throw err;
May 23 14:52:17 xenorchestra xo-server[1036]:     ^
May 23 14:52:17 xenorchestra xo-server[1036]: Error: Cannot find module 'bluebird'
May 23 14:52:17 xenorchestra xo-server[1036]:     at Function.Module._resolveFilename (module.js:548:15)
May 23 14:52:17 xenorchestra xo-server[1036]:     at Function.Module._load (module.js:475:25)
May 23 14:52:17 xenorchestra xo-server[1036]:     at Module.require (module.js:597:17)
May 23 14:52:17 xenorchestra xo-server[1036]:     at require (internal/module.js:11:18)
May 23 14:52:17 xenorchestra xo-server[1036]:     at Object.<anonymous> (/opt/xen-orchestra/packages/xo-server/bin/xo-server:17:18)
May 23 14:52:17 xenorchestra xo-server[1036]:     at Module._compile (module.js:653:30)
May 23 14:52:17 xenorchestra xo-server[1036]:     at Object.Module._extensions..js (module.js:664:10)
May 23 14:52:17 xenorchestra xo-server[1036]:     at Module.load (module.js:566:32)
May 23 14:52:17 xenorchestra xo-server[1036]:     at tryModuleLoad (module.js:506:12)
May 23 14:52:17 xenorchestra xo-server[1036]:     at Function.Module._load (module.js:498:3)
May 23 14:52:17 xenorchestra xo-server[1036]:     at Function.Module.runMain (module.js:694:10)
May 23 14:52:17 xenorchestra xo-server[1036]:     at startup (bootstrap_node.js:204:16)
May 23 14:52:17 xenorchestra xo-server[1036]:     at bootstrap_node.js:625:3
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Main process exited, code=exited, status=1/FAILURE
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Unit entered failed state.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Failed with result 'exit-code'.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Service hold-off time over, scheduling restart.
May 23 14:52:17 xenorchestra systemd[1]: Stopped XO Server.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Start request repeated too quickly.
May 23 14:52:17 xenorchestra systemd[1]: Failed to start XO Server.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Unit entered failed state.
May 23 14:52:17 xenorchestra systemd[1]: xo-server.service: Failed with result 'exit-code'.

#### Provide answers to these questions:

- Is this a fresh install or an upgrade?  fresh
- Version of XOCE server and web interface you're running latest
- What OS is XOCE running on? debian 9
- What method you used to install XOCE (xo_install.sh, manual installation, etc) This script
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console. Just what you see
- Include what you've done so far in the installation, and if you got any error messages along the way. basic install via script
- Indicate whether or not you've manually edited any data directly.

**Comment by GoodComputerGuy** [comment]
This is also happening to a friend who tried installing it last night, also on a Debian 9 VM.

**Comment by Jarli01** [comment]
I'm testing in a moment, but based on what is at the top it looks like your missing a dependency.

**Comment by GoodComputerGuy** [comment]
Thanks! My tech buddy and I are kind of linux newbs but all we did was a basic Debian 9 install, then ran your script. After both of us ran into the same issue I figured something was amiss.

**Comment by Jarli01** [comment]
Looks like ```apt-transport-https``` is missing from Debian 9.9.0, manually installing it first and then running the install appears to work. 

Still finishing up. 

But give this a try

```sudo rm -rf /opt/xen-orchestra```
```apt install apt-transport-https```
```sudo bash```
```sudo curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh | bash```

**Comment by Jarli01** [comment]
Another always viable option is to use the downstream, Ubuntu 19.04 server distro as well, which I believe has this, but it's a good to know dependency that can be added as to the troubleshooting page.

**Comment by Jarli01** [comment]
Yeah, your missing a dependency, specifically ```apt-transport-https``` at least from what I can see. 

Add the dependency and try again.

**Comment by GoodComputerGuy** [comment]
I added apt-transport-https no problem but then the script seemed to freeze here:
[16:28:32] Starting 'buildPages'...
[16:28:32] Starting 'buildScripts'...
[16:28:32] Starting 'buildStyles'...
[16:28:32] Starting 'copyAssets'...
Successfully compiled 1 file with Babel.
Successfully compiled 1 file with Babel.
Successfully compiled 8 files with Babel.
Successfully compiled 3 files with Babel.
Successfully compiled 4 files with Babel.
Successfully compiled 1 file with Babel.
Successfully compiled 1 file with Babel.
Successfully compiled 1 file with Babel.
Successfully compiled 3 files with Babel.
Successfully compiled 20 files with Babel.
Successfully compiled 9 files with Babel.
Successfully compiled 22 files with Babel.
[16:28:45] Finished 'buildPages' after 13 s
Successfully compiled 127 files with Babel.
[16:28:51] Finished 'buildStyles' after 19 s
[16:28:51] Finished 'copyAssets' after 19 s

Then I think I broke it getting a screen shot. Or maybe I just stopped it. If I've broken this too badly I can always start over with a fresh Debian install.

**Comment by Jarli01** [comment]
It takes a while for the build to complete if you allocated the minimum 1024mb of ram and 1 CPU. Like 2-4 minutes. 

	Successfully compiled 1 file with Babel.
	Successfully compiled 1 file with Babel.
	Successfully compiled 2 files with Babel.
	Successfully compiled 1 file with Babel.
	Successfully compiled 3 files with Babel.
	[16:21:18] Using gulpfile /opt/xen-orchestra/packages/xo-web/gulpfile.js
	[16:21:18] Starting 'build'...
	[16:21:18] Starting 'buildPages'...
	[16:21:18] Starting 'buildScripts'...
	[16:21:18] Starting 'buildStyles'...
	[16:21:18] Starting 'copyAssets'...
	Successfully compiled 9 files with Babel.
	Successfully compiled 5 files with Babel.
	Successfully compiled 1 file with Babel.
	Successfully compiled 3 files with Babel.
	Successfully compiled 1 file with Babel.
	Successfully compiled 1 file with Babel.
	Successfully compiled 4 files with Babel.
	Successfully compiled 8 files with Babel.
	Successfully compiled 1 file with Babel.
	Successfully compiled 1 file with Babel.
	Successfully compiled 3 files with Babel.
	Successfully compiled 20 files with Babel.
	Successfully compiled 9 files with Babel.
	Successfully compiled 22 files with Babel.
	[16:21:26] Finished 'buildPages' after 7.93 s
	[16:21:28] Finished 'copyAssets' after 10 s
	[16:21:33] Finished 'buildStyles' after 16 s
	Successfully compiled 127 files with Babel.
	[16:23:39] Finished 'buildScripts' after 2.35 min
	[16:23:39] Finished 'build' after 2.35 min
	Done in 166.76s.

**Comment by GoodComputerGuy** [comment]
Actually I had 2GB of RAM and 2 CPUs and a case of impatience. Waiting 244 seconds did the trick! Thanks - it looks like it's up and running now.

**Comment by Jarli01** [comment]
244 seconds is just over 4 minutes :-) my estimate wasn't too far off.

**Comment by GoodComputerGuy** [comment]
Yup! Thanks again. So is this a problem with the Debian version we're using? Or something you can modify in your script for future installs?

**Comment by Danp2** [comment]
The script can be improved to check for the missing dependency

**Comment by Jarli01** [comment]
@GoodComputerGuy thanks for the report, for new installs this should be taken care of automatically going forward.

**Comment by GoodComputerGuy** [comment]
No problem! Glad I could help out a little. Great scripts!
