### ISSUE TITLE
Error during installation xen orchestra debian 9

### ISSUE THREAD

**Issue by wesleylc1** [Jarli01/xenorchestra_installer#54]
**Describe the bug**
During the script execution stages, it returned the following error, but completed the installation successfully, when trying to access the web-gui, the "login and password" login credentials are requested, but it remains for minutes to load the information from the panel and nothing happens.

`70: v8::internal::Execution::Call(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, int, v8::internal::Handle<v8::internal::Object>*) [gulp build]
71: v8::Function::Call(v8::Local<v8::Context>, v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [gulp build]
72: v8::Function::Call(v8::Local<v8::Value>, int, v8::Local<v8::Value>*) [gulp build]
73: node::InternalCallbackScope::Close() [gulp build]
74: node::InternalMakeCallback(node::Environment*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*, node::async_context) [gulp build]
75: node::AsyncWrap::MakeCallback(v8::Local<v8::Function>, int, v8::Local<v8::Value>*) [gulp build]
76: 0x84fe53f [gulp build]
77: 0x85cdcc8 [gulp build]
78: 0x85d1787 [gulp build]
79: 0x85e2b23 [gulp build]
80: uv_run [gulp build]
81: node::Start(uv_loop_s*, int, char const* const*, int, char const* const*) [gulp build]
82: node::Start(int, char**) [gulp build]
83: main [gulp build]
84: __libc_start_main [/lib/i386-linux-gnu/libc.so.6]
Aborted
* xo-web:build − Error: 134
✖ 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-auth-github': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-auth-google': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-auth-ldap': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-auth-saml': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-backup-reports': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-cloud': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-load-balancer': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-perf-alert': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-test-plugin': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-transport-email': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-transport-nagios': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-transport-slack': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-transport-xmpp': File exists
ln: failed to create symbolic link '/usr/local/lib/node_modules/xo-server-usage-report': File exists
`
****To Reproduce**
Steps to reproduce the behavior:**

_After some unsuccessful tests, I chose to remove the "/ opt / xen-orchestra /" folder and perform a new installation, but the same error occurred._

****Expected behavior**
A clear and concise description of what you expected to happen.**

_After a new installation, I was waiting for a successful installation._

****Screenshots**
If applicable, add screenshots to help explain your problem.**

https://ibb.co/FbRXKhd
https://ibb.co/VS1Npk2
https://ibb.co/LrBVb40
https://ibb.co/2N3yKpt

**Desktop/Server details (please complete the following information):**
 - OS: [Debian GNU/Linux 9.9 (stretch) i386]
 - Browser [Google Chrome 75.0.3770.80, Firefoz Quantum 67.0, Internet Explorer 11]

**Additional context**

****Confirm XOCE services are running**
Please run ```systemctl status xo-server.service``` and paste the resulting output below.** 

`(18:01:51) root@prjxoce936v /opt/xen-orchestra]# systemctl status xo-server.service
● xo-server.service - XO Server
   Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2019-06-14 17:24:14 -03; 37min ago
 Main PID: 6078 (node)
    Tasks: 52 (limit: 4915)
   CGroup: /system.slice/xo-server.service
           ├─6078 /usr/local/bin/node ./bin/xo-server
           ├─6093 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/workers/processChild.js
           ├─6098 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/workers/processChild.js
           ├─6104 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/workers/processChild.js
           ├─6106 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/workers/processChild.js
           ├─6111 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/workers/processChild.js
           ├─6121 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/workers/processChild.js
           └─6126 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/workers/processChild.js

Jun 14 18:00:08 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 965 ms
Jun 14 18:00:09 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 1000 ms
Jun 14 18:00:10 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 1988 ms
Jun 14 18:00:12 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 3018 ms
Jun 14 18:00:15 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 4927 ms
Jun 14 18:00:20 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 7953 ms
Jun 14 18:00:28 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 12495 ms
Jun 14 18:00:41 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 21604 ms
Jun 14 18:01:02 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 32305 ms
Jun 14 18:01:35 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 57400 ms
`

****Provide the output of journalctl logs**
Please run ```journalctl -u xo-server -f -n 50``` and paste the resulting output below.** 

`[(17:52:43) root@prjxoce936v /opt/xen-orchestra]#    journalctl -u xo-server -f -n 50
-- Logs begin at Fri 2019-06-14 16:58:34 -03. --
Jun 14 17:50:35 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 3031 ms
Jun 14 17:50:38 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 5201 ms
Jun 14 17:50:43 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 7917 ms
Jun 14 17:50:51 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 13628 ms
Jun 14 17:51:05 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 20157 ms
Jun 14 17:51:25 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 35011 ms
Jun 14 17:52:00 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 56645 ms
Jun 14 17:52:56 prjxoce936v xo-server[6078]: xo-server-cloud: fail to connect to updater ErrorEvent {
Jun 14 17:52:56 prjxoce936v xo-server[6078]:   target:
Jun 14 17:52:56 prjxoce936v xo-server[6078]:    WebSocket {
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      domain: null,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _events: {},
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _eventsCount: 0,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _maxListeners: undefined,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      readyState: 3,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      protocol: '',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _binaryType: 'nodebuffer',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _closeFrameReceived: false,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _closeFrameSent: false,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _closeMessage: '',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _closeTimer: null,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _closeCode: 1006,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _extensions: {},
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _receiver: null,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _sender: null,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _socket: null,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _isServer: false,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _redirects: 0,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      url: 'ws://localhost:9001',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      _req: null },
Jun 14 17:52:56 prjxoce936v xo-server[6078]:   type: 'error',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:   message: 'connect ECONNREFUSED 127.0.0.1:9001',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:   error:
Jun 14 17:52:56 prjxoce936v xo-server[6078]:    { Error: connect ECONNREFUSED 127.0.0.1:9001
Jun 14 17:52:56 prjxoce936v xo-server[6078]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      errno: 'ECONNREFUSED',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      code: 'ECONNREFUSED',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      syscall: 'connect',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      address: '127.0.0.1',
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      port: 9001,
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      [Symbol(originalCallSite)]: [ CallSite {} ],
Jun 14 17:52:56 prjxoce936v xo-server[6078]:      [Symbol(mutatedCallSite)]: [ CallSite {} ] } }
Jun 14 17:52:56 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 977 ms
Jun 14 17:52:57 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 967 ms
Jun 14 17:52:58 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 1964 ms
Jun 14 17:53:00 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 2943 ms
Jun 14 17:53:03 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 4976 ms
Jun 14 17:53:08 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 8102 ms
Jun 14 17:53:16 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 13037 ms
Jun 14 17:53:29 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 21882 ms
Jun 14 17:53:51 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 34916 ms
Jun 14 17:54:26 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 55807 ms
Jun 14 17:55:22 prjxoce936v xo-server[6078]: xo-server-cloud: fail to connect to updater ErrorEvent {
Jun 14 17:55:22 prjxoce936v xo-server[6078]:   target:
Jun 14 17:55:22 prjxoce936v xo-server[6078]:    WebSocket {
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      domain: null,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _events: {},
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _eventsCount: 0,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _maxListeners: undefined,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      readyState: 3,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      protocol: '',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _binaryType: 'nodebuffer',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _closeFrameReceived: false,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _closeFrameSent: false,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _closeMessage: '',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _closeTimer: null,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _closeCode: 1006,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _extensions: {},
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _receiver: null,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _sender: null,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _socket: null,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _isServer: false,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _redirects: 0,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      url: 'ws://localhost:9001',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      _req: null },
Jun 14 17:55:22 prjxoce936v xo-server[6078]:   type: 'error',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:   message: 'connect ECONNREFUSED 127.0.0.1:9001',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:   error:
Jun 14 17:55:22 prjxoce936v xo-server[6078]:    { Error: connect ECONNREFUSED 127.0.0.1:9001
Jun 14 17:55:22 prjxoce936v xo-server[6078]:     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      errno: 'ECONNREFUSED',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      code: 'ECONNREFUSED',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      syscall: 'connect',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      address: '127.0.0.1',
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      port: 9001,
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      [Symbol(originalCallSite)]: [ CallSite {} ],
Jun 14 17:55:22 prjxoce936v xo-server[6078]:      [Symbol(mutatedCallSite)]: [ CallSite {} ] } }
Jun 14 17:55:22 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 999 ms
Jun 14 17:55:23 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 986 ms
Jun 14 17:55:24 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 1954 ms
Jun 14 17:55:26 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 2881 ms
Jun 14 17:55:29 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 4754 ms
Jun 14 17:55:34 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 7813 ms
Jun 14 17:55:41 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 12780 ms
Jun 14 17:55:54 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 20702 ms
Jun 14 17:56:15 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 33842 ms
Jun 14 17:56:49 prjxoce936v xo-server[6078]: xo-server-cloud: next attempt in 54393 ms

`

**Provide answers to these questions:**

*** Is this a fresh install or an upgrade?**
_is a new installation._

* Version of XOCE server and web interface you're running
*** What OS is XOCE running on?**
_Debian GNU/Linux 9.9 (stretch)_

*** What method you used to install XOCE (xo_install.sh, manual installation, etc)**
_curl https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh | bash

On the second install, I downloaded the script and executed it manually using the command "./xo_install.sh"
wget https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xo_install.sh_

*** What specific XOCE page you're on, and what specific element you're interacting with to trigger the error**
_When I try to access web-gui_

*** Any errors that appear in your browser's error console.**
_It does not display error, it just does not connect to the console._

*** Indicate whether or not you've manually edited any data directly.**

_I have not made any changes._

**Comment by Danp2** [comment]
Hi @wesleylc1,

I can look into this for you. Did you attempt to perform the manual installation using the "official" docs? If so, did that work without error?

Dan

**Comment by Danp2** [comment]
FYI, I ran both a manual installation and the scripted one and both processes completed successfully. Suggest that you try again as I suspect this was due to an upstream issue.

**Comment by wesleylc1** [comment]
@Danp2 
I apologize for the delay in my return, but, according to your suggestion, I performed a new installation through an VM X64 works.
