### ISSUE TITLE
Add a disclaimer in the README saying that the installation script is not provided by XO team

### ISSUE THREAD

**Issue by stormi** [Jarli01/xenorchestra_installer#55]
Following this discussion where a user was told by another user that these installation scripts are the official way to install XenOrchestra from sources, I suggest to add a visible note to the README that says that these are convenience scripts provided by the community, not official scripts provided by the Xen Orchestra developers, and that the official way to install from sources is this: https://xen-orchestra.com/docs/from_the_sources.html

Note: I've not been mandated by Olivier to open this bug report :)

**Comment by Jarli01** [comment]
I'd be welcome to make an edit such as that if Olivier would welcome adding scripted installation information to the source documents.

This script, literally automates the install process, the only difference is that Olivier and team didn't write the script and that this script makes sure that the intended installation guest has the dependencies (and removes things that are anti-open).

**Comment by Danp2** [comment]
I don't think this needs to be a "tit for tat" situation. We can easily add a disclaimer to the readme document. I think it would be good to also expand the script to include some details as the final step on how to get further help if needed.

That said, it would be nice if the development team weren't so quick to "direct" blame towards these installation scripts before checking their own work. 😉

**Comment by Jarli01** [comment]
@Danp2 that's essentially the point of getting them to concede that this script isn't the culprit of everything that goes wrong.

But it does raise the question, is @stormi going to ask every installation script to do the same thing? In terms of official support, you and I officially support installations who use this script. 

But, with that, what would such a script look like? We already make it pretty obvious that this is a community project (it's in the name). We could change all of the URLs to point to this GH page for support, but Olivier said he'd prefer if we didn't, but instead add an additional URL to the support section etc.

**Comment by Danp2** [comment]
> that's essentially the point of getting them to concede that this script isn't the culprit of everything that goes wrong.

I think we're essentially stating the same thing, just at different degrees of "resistance". If you will take the emotion out of the equation, then I think we can move forward and implement these changes without too much fan fare. 😄 

>  is @stormi going to ask every installation script to do the same thing?

Does it really matter? The bottom line is that we want to be a "good citizen" when it comes to supporting this project (XO). As such, I don't see it being a big deal to clarify the situation to state that "this script automates the process of installing XO. See this link to review the manual process" or whatever.

**Comment by Jarli01** [comment]
https://github.com/Jarli01/xenorchestra_installer/pull/56

**Comment by Jarli01** [comment]
@stormi thanks for the recommendation, I've created a PR, if @Danp2 and you think it would help to fix the misunderstanding that exist today I'm happy to merge it into the readme.

**Comment by Jarli01** [comment]
Closing per https://github.com/Jarli01/xenorchestra_installer/pull/56
