### ISSUE TITLE
The "SMB" mount point failed.

### ISSUE THREAD

**Issue by wesleylc1** [Jarli01/xenorchestra_installer#57]
Hello Guys,
Has anyone ever had problems while trying to map SMB shares?

`Command failed: mount -t cifs //192.168.42.229\restauracao/" /run/xo-server/mounts/c663ac4e-f7bd-4a6f-9a21-8ad180d01b37 -o domain=WORKGROUP
mount error(2): No such file or directory
Refer to the mount.cifs(8) manual page (e.g. man mount.cifs)`

[https://ibb.co/YkVrJhm](https://ibb.co/YkVrJhm)

**Comment by Jarli01** [comment]
Your screenshot is actually a link to this issues page, but usually this is because of a mistake in your setup of the mount point.

**Comment by Jarli01** [comment]
Did you have the nfs-common utility installed on this XO installation?

**Comment by wesleylc1** [comment]
@Jarli01
now I'm not in the company, but tomorrow I can check this information.

**Comment by Danp2** [comment]
> nfs-common

Would this even be applicable since he is trying to attach to an SMB share?

@wesleylc1 Can you tell us more about these shares? Are these Windows machines?

**Comment by wesleylc1** [comment]
> Did you have the nfs-common utility installed on this XO installation?

Hi, the "nfs-common" package is already installed.

https://ibb.co/D40yh4F

**Comment by Jarli01** [comment]
> Would this even be applicable since he is trying to attach to an SMB share?

Yes, as the nfs-common provides the cifs details (which is SMB) connectivity. 

Since this is installed, my guess is the way you have this connection setup within XO and not an issue with the installation

**Comment by wesleylc1** [comment]
@Jarli01 
I did not make changes, I just tried a new connection and I was successful.

https://ibb.co/HqW0szr

**Comment by Jarli01** [comment]
@wesleylc1 there is likely something going on with your SMB server if it is having connection issues. But so long as it worked,just keep an eye on it. 

Is this issue still needing to remain open?

**Comment by wesleylc1** [comment]
@Jarli01 
Thanks for the help, but it can be closed.
