### ISSUE TITLE
Review sed usage

### ISSUE THREAD

**Issue by Danp2** [Jarli01/xenorchestra_installer#60]
Seems like this line is no longer working --

https://github.com/Jarli01/xenorchestra_installer/blob/a3753004a9f35e63370d121e64ecc742dffb9622/xo_install.sh#L57

Suggest that it be removed entirely as the defaults seem to be working as-is. See https://github.com/vatesfr/xen-orchestra/commit/31266728f70c625e155e38fe5795f941d6565dd2#diff-975a16af1b49efb1359689848132de33 for details on changes to original source.

**Comment by Danp2** [comment]
@Jarli01 Thougts?

**Comment by Jarli01** [comment]
I'm testing this now

**Comment by Jarli01** [comment]
This worked on my test system, go ahead and merge it

**Comment by Danp2** [comment]
Closed by 5c8c4c38855aa3170caaf1e6cd0929a6ee7c0def
