### ISSUE TITLE
XO Hub

### ISSUE THREAD

**Issue by astrugatch** [Jarli01/xenorchestra_installer#63]
**Describe the bug**
No VMs available in XO Hub. Not sure if I'm misunderstanding how this feature works or if its just not available in the CE

**To Reproduce**
Open the "Hub" option on the main menu and see "No VMs available"

**Expected behavior**
List of deployable templates

**Screenshots**

**Desktop/Server details (please complete the following information):**
 - OS: Ubuntu 18.10
 - Browser Chrome
 - Version xoserver 5.51.1

**Additional context**

**Confirm XOCE services are running**
Please run ```systemctl status xo-server.service``` and paste the resulting output below. 

**Provide the output of journalctl logs**
Please run ```journalctl -u xo-server -f -n 50``` and paste the resulting output below. 

**Provide answers to these questions:**
* Is this a fresh install or an upgrade? upgrade
* Version of XOCE server and web interface you're running 5.51.1
* What OS is XOCE running on? 18.10
* What method did you use to install XOCE (xo_install.sh, manual installation, etc)xo_install.sh

**Comment by astrugatch** [comment]
Just saw the thread in the forum about this only being available in XOA. 

https://xcp-ng.org/forum/topic/2016/hub-templates

**Comment by Jarli01** [comment]
Sorry can't fix that.
