### ISSUE TITLE
Node LTS is now the recommended version

### ISSUE THREAD

**Issue by Danp2** [Jarli01/xenorchestra_installer#68]
From https://xen-orchestra.com/docs/from_the_sources.html --

> XO needs Node.js. Please use Node LTS.

Following line should be updated --
https://github.com/Jarli01/xenorchestra_installer/blob/821375b674f2f898f10798bc7d071c758cba7d98/xo_install.sh#L41

**Comment by Jarli01** [comment]
Just jumping to LTS doesn't work, The install is still attempting to use 8.10 even though 12.16.1 is installed. 

Attached install log. 

[install.log](https://github.com/Jarli01/xenorchestra_installer/files/4427214/install.log)

**Comment by Jarli01** [comment]
We also need an updated n repo, as this is point to 6.4.0 which only supports up to 8 

`n_repo="https://raw.githubusercontent.com/visionmedia/n/master/bin/n"`

**Comment by Danp2** [comment]
Haven't tried a clean install, but a simple `n lts` was enough to update my XO VM's node version.

**Comment by Danp2** [comment]
This crashes for me at the tail end of the `yarn build` process

**Comment by Jarli01** [comment]
Without the n change above the install completed, but had issues with xo_web near the end.

**Comment by Danp2** [comment]
> Using targets:
{
  "node": "8.10"
}

I've notice this, but wasn't sure if it was pertinent. FWIW, switching back to node 8.16 and the `yarn build` successfully compiles. I'll do more testing, but this might need to be "kicked up" to the devs for feedback. Obviously, they're going to want proof that this same thing occurs when you build manually from source. 😈

**Comment by Jarli01** [comment]
Yeah...

**Comment by Danp2** [comment]
Performing a manual build now. Saw the same "node 8.10" messages, so I'm guessing that it's benign.

Build still fails. Looks like it's a memory issue. Will bump up the VM's memory from 2 to 4GB and retry.

**Comment by Danp2** [comment]
Manual build was successful when using 4GB. Now to retest with scripted version

**Comment by Jarli01** [comment]
With just the n lts change? If so I have a build running right now

**Comment by Jarli01** [comment]
If 4GB is needed, this needs to get changed too

    # Check for 1GB Memory
    totalk=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
    if [ "$totalk" -lt "1000000" ]; then echo "XOCE Requires at least 1GB Memory!"; exit 1; fi 

to 

    # Check for 4GB Memory
    totalk=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
    if [ "$totalk" -lt "4000000" ]; then echo "XOCE Requires at least 1GB Memory!"; exit 1; fi

**Comment by Danp2** [comment]
Right... I was planning to do that. I'm testing now with 3GB to see if that will suffice.

**Comment by Danp2** [comment]
And it just completed successfully, so I'll bump to requirement to 3 instead of 4.

**Comment by Jarli01** [comment]
Node is getting ram heavy, used to be we could install with 256mb of ram.

**Comment by Jarli01** [comment]
If 3GB works, this section should read

# Check for 3GB Memory
totalk=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
if [ "$totalk" -lt "3064584" ]; then echo "XOCE Requires at least 1GB Memory!"; exit 1; fi

**Comment by Danp2** [comment]
I made the change, but used 300000 instead of 3064584. Your echo is still wrong. ;-)

P.S. Just noticed that XOA is still using 2GB. Wonder if there is anything we could do to reduce the memory requirements?

**Comment by Jarli01** [comment]
> Your echo is still wrong. ;-)

Fixed, do you know off hand if they are using the same node version and OS?

**Comment by Danp2** [comment]
Just left a comment at https://github.com/vatesfr/xen-orchestra/issues/4787

**Comment by Danp2** [comment]
Good question... Looks like they are running node 12.16.1 and debian 10. I've been testing with Ubuntu 19.10

**Comment by Jarli01** [comment]
The OS may have different requirements. . . it may be better to stick with the 3GB limitation anyways, as these backup operations are requiring more ram anyways.

**Comment by Danp2** [comment]
Closed in #69
