### ISSUE TITLE
error while restarting server

### ISSUE THREAD

**Issue by icrfornax** [Jarli01/xenorchestra_installer#72]
Hello Jarli :-)
tanks for your script. I am new to XCP and still experimenting creating, moving, backuping VMs etc.
I came to your script which will do the whole self compiling ... GREAT!
But here is the (authentification-) error, xo-server.service is reporting:
(system is a fresh Ubuntu 20.04; nothing special, fresh install; tried it also as root)

root@ubuntu2004lts:/home/icr# systemctl status xo-server.service
● xo-server.service - XO Server
     Loaded: loaded (/lib/systemd/system/xo-server.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2020-05-01 19:38:46 UTC; 3h 51min ago
   Main PID: 4652 (node)
      Tasks: 18 (limit: 4578)
     Memory: 75.2M
     CGroup: /system.slice/xo-server.service
             ├─4652 /usr/local/bin/node ./bin/xo-server
             └─4667 /usr/local/bin/node /opt/xen-orchestra/node_modules/jest-worker/build/workers/processChild.js

Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:       at _default.authenticateUser (/opt/xen-orchestra/packages/xo-server/src/xo-mixins/authentication.js:1>
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:       at Xo.authenticateUser (/opt/xen-orchestra/node_modules/lodash/_createBind.js:23:15)
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:       at Strategy._verify (/opt/xen-orchestra/packages/xo-server/src/index.js:283:35)
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:       at Strategy.authenticate (/opt/xen-orchestra/node_modules/passport-local/lib/strategy.js:90:12)
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:       at attempt (/opt/xen-orchestra/node_modules/passport/lib/middleware/authenticate.js:366:16) {
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:     command: 'SINTER',
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:     code: 'NR_CLOSED',
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:     args: [ 'xo:user_email:admin@admin.net' ]
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]:   }
Mai 01 23:28:32 ubuntu2004lts xo-server[4652]: }

Maybe others experience this too?

**Comment by icrfornax** [comment]
sry: forgot the login-prompt screenshot

![image](https://user-images.githubusercontent.com/5561388/80849041-cc6b3000-8c15-11ea-9d74-653cc9e54fdf.png)

**Comment by Jarli01** [comment]
Can you provide a link to the ISO you used (I'll test this right now).

Also please answer the questions in the template

**Comment by icrfornax** [comment]
Hi - NP :-) Current ISO XCP 8.1.0.2 clean install. (https://xcp-ng.org/  "latest ISO)

Only "issue" DOM0 Prob - therefor using 2GB memory version to install. Normal XOA (deploy after installation via IP) seem to run without problems.

"Server" is an AMD Ryzen7 2700 8Core, B450 Chipset, 64GB RAM / "Homelab"
Using 4GB of RAM for the XOCE-VM.

Because of "stucked in installation", most of the questions (log...) could not be answered, sorry.

Do not know, if this helps:
 journalctl -u xo-server -f -n 50
icr@ubuntu2004lts:~$  journalctl -u xo-server -f -n 50
-- Logs begin at Wed 2020-04-29 22:09:27 UTC. --
Mai 02 18:55:13 ubuntu2004lts xo-server[714]: 2020-05-02T18:55:13.796Z xo:xo-server ERROR unhandled error event {
Mai 02 18:55:13 ubuntu2004lts xo-server[714]:   error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Mai 02 18:55:13 ubuntu2004lts xo-server[714]:       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
Mai 02 18:55:13 ubuntu2004lts xo-server[714]:     errno: 'ECONNREFUSED',
Mai 02 18:55:13 ubuntu2004lts xo-server[714]:     code: 'ECONNREFUSED',
Mai 02 18:55:13 ubuntu2004lts xo-server[714]:     syscall: 'connect',
Mai 02 18:55:13 ubuntu2004lts xo-server[714]:     address: '127.0.0.1',
Mai 02 18:55:13 ubuntu2004lts xo-server[714]:     port: 6379
Mai 02 18:55:13 ubuntu2004lts xo-server[714]:   }
Mai 02 18:55:13 ubuntu2004lts xo-server[714]: }
Mai 02 18:55:18 ubuntu2004lts xo-server[714]: 2020-05-02T18:55:18.629Z xo:xo-server ERROR unhandled error event {
Mai 02 18:55:18 ubuntu2004lts xo-server[714]:   error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Mai 02 18:55:18 ubuntu2004lts xo-server[714]:       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
Mai 02 18:55:18 ubuntu2004lts xo-server[714]:     errno: 'ECONNREFUSED',
Mai 02 18:55:18 ubuntu2004lts xo-server[714]:     code: 'ECONNREFUSED',
Mai 02 18:55:18 ubuntu2004lts xo-server[714]:     syscall: 'connect',
Mai 02 18:55:18 ubuntu2004lts xo-server[714]:     address: '127.0.0.1',
Mai 02 18:55:18 ubuntu2004lts xo-server[714]:     port: 6379
Mai 02 18:55:18 ubuntu2004lts xo-server[714]:   }
Mai 02 18:55:18 ubuntu2004lts xo-server[714]: }
Mai 02 18:55:26 ubuntu2004lts xo-server[714]: 2020-05-02T18:55:26.846Z xo:xo-server ERROR unhandled error event {
Mai 02 18:55:26 ubuntu2004lts xo-server[714]:   error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Mai 02 18:55:26 ubuntu2004lts xo-server[714]:       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
Mai 02 18:55:26 ubuntu2004lts xo-server[714]:     errno: 'ECONNREFUSED',
Mai 02 18:55:26 ubuntu2004lts xo-server[714]:     code: 'ECONNREFUSED',
Mai 02 18:55:26 ubuntu2004lts xo-server[714]:     syscall: 'connect',
Mai 02 18:55:26 ubuntu2004lts xo-server[714]:     address: '127.0.0.1',
Mai 02 18:55:26 ubuntu2004lts xo-server[714]:     port: 6379
Mai 02 18:55:26 ubuntu2004lts xo-server[714]:   }
Mai 02 18:55:26 ubuntu2004lts xo-server[714]: }
Mai 02 18:55:40 ubuntu2004lts xo-server[714]: 2020-05-02T18:55:40.241Z xo:xo-server ERROR unhandled error event {
Mai 02 18:55:40 ubuntu2004lts xo-server[714]:   error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Mai 02 18:55:40 ubuntu2004lts xo-server[714]:       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
Mai 02 18:55:40 ubuntu2004lts xo-server[714]:     errno: 'ECONNREFUSED',
Mai 02 18:55:40 ubuntu2004lts xo-server[714]:     code: 'ECONNREFUSED',
Mai 02 18:55:40 ubuntu2004lts xo-server[714]:     syscall: 'connect',
Mai 02 18:55:40 ubuntu2004lts xo-server[714]:     address: '127.0.0.1',
Mai 02 18:55:40 ubuntu2004lts xo-server[714]:     port: 6379
Mai 02 18:55:40 ubuntu2004lts xo-server[714]:   }
Mai 02 18:55:40 ubuntu2004lts xo-server[714]: }
Mai 02 18:56:03 ubuntu2004lts xo-server[714]: 2020-05-02T18:56:03.994Z xo:xo-server ERROR unhandled error event {
Mai 02 18:56:03 ubuntu2004lts xo-server[714]:   error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Mai 02 18:56:03 ubuntu2004lts xo-server[714]:       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
Mai 02 18:56:03 ubuntu2004lts xo-server[714]:     errno: 'ECONNREFUSED',
Mai 02 18:56:03 ubuntu2004lts xo-server[714]:     code: 'ECONNREFUSED',
Mai 02 18:56:03 ubuntu2004lts xo-server[714]:     syscall: 'connect',
Mai 02 18:56:03 ubuntu2004lts xo-server[714]:     address: '127.0.0.1',
Mai 02 18:56:03 ubuntu2004lts xo-server[714]:     port: 6379
Mai 02 18:56:03 ubuntu2004lts xo-server[714]:   }
Mai 02 18:56:03 ubuntu2004lts xo-server[714]: }
Mai 02 18:56:44 ubuntu2004lts xo-server[714]: 2020-05-02T18:56:44.342Z xo:xo-server ERROR unhandled error event {
Mai 02 18:56:44 ubuntu2004lts xo-server[714]:   error: Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379
Mai 02 18:56:44 ubuntu2004lts xo-server[714]:       at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
Mai 02 18:56:44 ubuntu2004lts xo-server[714]:     errno: 'ECONNREFUSED',
Mai 02 18:56:44 ubuntu2004lts xo-server[714]:     code: 'ECONNREFUSED',
Mai 02 18:56:44 ubuntu2004lts xo-server[714]:     syscall: 'connect',
Mai 02 18:56:44 ubuntu2004lts xo-server[714]:     address: '127.0.0.1',
Mai 02 18:56:44 ubuntu2004lts xo-server[714]:     port: 6379
Mai 02 18:56:44 ubuntu2004lts xo-server[714]:   }
Mai 02 18:56:44 ubuntu2004lts xo-server[714]: }

**Comment by Danp2** [comment]
Please post the output of `node -v` (please use markdown syntax when posting)

**Comment by icrfornax** [comment]
Hi - node -version is v12.16.3

**Comment by Danp2** [comment]
Please reset your XO config with the following commands and then repost the log output after the service restart --

```
    redis-cli flushall
    systemctl restart xo-server.service
```

**Comment by icrfornax** [comment]
Hi, sorry, took me a while to anser:
1)
```
root@ubuntu2004lts:/home/icr# redis-cli flushall
Command 'redis-cli' not found, but can be installed with:
apt install redis-tools
...
root@ubuntu2004lts:/home/icr# redis-cli flushall
Could not connect to Redis at 127.0.0.1:6379: Connection refused
```
Seems like a Problem with the Port --> checking

searched for file /etc/redis/redis.conf
to change
`bind 127.0.0.1`
to
`bind 0.0.0.0`
and re-run sudo service redis-server 

```
root@ubuntu2004lts:/home/icr# locate redis-cli
/usr/bin/redis-cli
/usr/share/bash-completion/completions/redis-cli
/usr/share/man/man1/redis-cli.1.gz

root@ubuntu2004lts:/home/icr# locate redis.conf
root@ubuntu2004lts:/home/icr# 

root@ubuntu2004lts:/home/icr# systemctl status redis-server
Unit redis-server.service could not be found.
root@ubuntu2004lts:/home/icr# 

```
For me, it looks like, redis is not installed :-)

**Comment by icrfornax** [comment]
```
root@ubuntu2004lts:/home/icr# # Install XO dependencies
root@ubuntu2004lts:/home/icr# /usr/bin/apt-get install --yes build-essential redis-server libpng-dev git python-minimal libvhdi-utils nfs-common lvm2 cifs-utils 
Packet lists are read... Done
Dependency tree is built.       
Status information is read in... Ready
package python-minimal is not available, but is supported by another package
referenced. This can mean that the package is missing, that it has been replaced
or is only available from another source.
But the following packages replace it:
  python2-minimal

E: There is no installation candidate for package "python-minimal".
root@ubuntu2004lts:/home/icr# 
```

**Comment by icrfornax** [comment]
... sorry to send the comments toooo often :-)

works with:
```
root@ubuntu2004lts:/home/icr# # Install XO dependencies
root@ubuntu2004lts:/home/icr# /usr/bin/apt-get install --yes build-essential redis-server libpng-dev git **python2-minimal** libvhdi-utils nfs-common lvm2 cifs-utils 
```

**Comment by icrfornax** [comment]
DAMN it - sorry, pressing wrong buttons here and sending toooo many comments :-(

works with: **python2-minimal**
```
root@ubuntu2004lts:/home/icr# # Install XO dependencies
root@ubuntu2004lts:/home/icr# /usr/bin/apt-get install --yes build-essential redis-server libpng-dev git python2-minimal libvhdi-utils nfs-common lvm2 cifs-utils 
```

**Comment by icrfornax** [comment]
WORKED !

![image](https://user-images.githubusercontent.com/5561388/81108398-ed36cc80-8f18-11ea-8a04-43efc0e39da6.png)

**Comment by Danp2** [comment]
Found this -- https://meterpreter.org/developers-continue-to-remove-python-2-from-ubuntu-20-04-lts/

**Comment by icrfornax** [comment]
:-) 
const $change

Thanks a lot. I will now discover the XOCE Server!
