### ISSUE TITLE
Hosts and VMs - blank console page on XO from source 5.59.0

### ISSUE THREAD

**Issue by gskger** [Jarli01/xenorchestra_installer#73]
I am runing XO from source 5.59.0 build with your script on a fully patched Debian Buster VM (2 vCPU, 2GiB RAM, 10 GiB storage) in a fully patched two node XCP-ng 8.1 cluster (DELL R210 II, 32GiB RAM, NAS).

When I go to the console tab of any host or any VM, the console windows is not shown (page is blank, except for the info graphics at the top of the page). I am using current Chrome or Firefox browser on a Windows 10 Pro maschine.

When accessing the console tab `tailf /var/log/syslog` gives 
`May  2 17:45:35 e2052 xo-server[9259]: 2020-05-02T15:45:35.867Z xo:main INFO + Console proxy (admin - ::ffff:192.168.10.11)`
`May  2 17:45:35 e2052 xo-server[9259]: 2020-05-02T15:45:35.891Z xo:proxy-console DEBUG connected`
`May  2 17:45:46 e2052 xo-server[9259]: 2020-05-02T15:45:46.562Z xo:main INFO - Console proxy (admin - ::ffff:192.168.10.11)`
`May  2 17:45:46 e2052 xo-server[9259]: 2020-05-02T15:45:46.562Z xo:proxy-console DEBUG disconnected from the XO client`
`May  2 17:46:00 e2052 xo-server[9259]: [load-balancer]Execute plans!`
(Upps, no line breaks with code markup?)

When I access the host or VM through XCP-ng Center (build 20.04.00.32), the console window is shown.
Any idea how to get the console windows back in XO from Source?

**Comment by Jarli01** [comment]
This has been a sporadic issue since XO was released. I've not been able to find a solution and have the same console issue with xcp-ng as well. 

This, generally speaking seems like an upstream issue that the XO Devs would need to investigate.

**Comment by Danp2** [comment]
Does the console work if you use XOA instead? Are you behind a proxy? Are there multiple networks involved?

**Comment by rjt** [comment]
Do you have static IP addresses assigned to all hosts and xo as well?   Not
just static dhcp leases but manual static IP setup.   One problem with
machines being so fast is that services are attempting to do network things
before the network is up and then crash.
