### ISSUE TITLE
Only fully operational on Ubuntu 18.04?

### ISSUE THREAD

**Issue by MisterBaz** [Jarli01/xenorchestra_installer#74]
**Describe the bug**
This only works 100% on Ubuntu 18.04 (server) for me.  19.10 only opens port 80.  20.04 finishes installing "successfully" but has no listening ports on 80 or 443.

**To Reproduce**
1. Use Ubuntu 19.10 or newer

**Expected behavior**
Install script completes and opens ports 80 and 443.

**Desktop/Server details (please complete the following information):**
 - OS: Ubuntu 18.04, 19.10, and 20.04
 - Browser: FireFox/Chrome/IE

**Additional context**
Running on XCP-NG 8.1

**Confirm XOCE services are running**
Yes, in each case I've confirmed the xo-server is running.  I've even restarted it.

**Provide the output of journalctl logs**
Please run ```journalctl -u xo-server -f -n 50``` and paste the resulting output below. 

**Provide answers to these questions:**
* Is this a fresh install or an upgrade?
 -- Fresh install on all Ubuntu versions
* Version of XOCE server and web interface you're running
* What OS is XOCE running on?
 --  Ubuntu Server
* A link to the ISO you've used as as the server (so we can verify/troubleshoot)
 -- Literally just downloaded them this week from Ubuntu's mirrors 
* What method did you use to install XOCE (xo_install.sh, manual installation, etc)
 -- xo_install.sh
* What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
 -- Install finishes fine.  The ports aren't opening on newer builds of Ubuntu
* If a stacktrace is provided in the error, include that too.
* Any errors that appear in your browser's error console.
 -- Just a 404
* Include what you've done so far in the installation, and if you got any error messages along the way.
* Indicate whether or not you've manually edited any data directly.
 -- Nothing.  Install Ubuntu.  Run apt-update and subsequently apt-upgrade, then run the XO installer.

**Comment by Jarli01** [comment]
You've left so much information as non helpful...

Are you making changes to your Ubuntu installation before running the installation process?

**Comment by Danp2** [comment]
There's a known issue with Ubuntu 20.04. More details can be fund in #72. It's possible that they have also started removing the `python-minimal` package from earlier releases. Can you post the output of `whereis python` from each of your installs?

**Comment by Jarli01** [comment]
What resources does your VM have as well, vCPU and RAM totals.

**Comment by MisterBaz** [comment]
2 vCPU, 4G RAM, 25G drive space.

I'm doing literally nothing other than installing Ubuntu Server from ISO.  I then perform an apt-update and apt-upgrade.  Reboot.  Then run the install script.  After that, port 80 works, but not https.  I then run the xo-update.sh script.  It completes successfully.  Still only http through port 80.

**Comment by Jarli01** [comment]
HTTPS needs to be enabled by following the documentation https://xen-orchestra.com/docs/configuration.html#https

I'm testing 20.04 right now and will propose an update to it if needed.

**Comment by MisterBaz** [comment]
> 
> 
> There's a known issue with Ubuntu 20.04. More details can be fund in #72. It's possible that they have also started removing the `python-minimal` package from earlier releases. Can you post the output of `whereis python` from each of your installs?

I did notice something during the install saying python-minimal was deprecated and to use python2-minimal instead.

whereis returns:
python: /usr/bin/python /usr/bin/python3.7m /usr/bin/python2.7 /usr/bin/python3.7 /usr/lib/python2.7 /usr/libpython3.7 /usr/lib/python3.8 /etc/python /etc/python2.7 /etc/python3.7 /usr/local/lib/python2.7 /usr/local/lib/python3.7 /usr/share/python /usr/share/man/man1/python.1.gz

**Comment by MisterBaz** [comment]
> 
> 
> HTTPS needs to be enabled by following the documentation https://xen-orchestra.com/docs/configuration.html#https
> 
> I'm testing 20.04 right now and will propose an update to it if needed.

Where is the config.toml file?  I have no directory /etc/xo-server

**Comment by Jarli01** [comment]
We install to `/opt/xen_orchestra/`

**Comment by MisterBaz** [comment]
Thanks.  Sorry for the delay.  I had forgotten the extra steps to enabling https.  It has been a while.
I was able to get everything working on Ubuntu 19.10.
