### ISSUE TITLE
Unable to get the universe and multiverse repositories to install the required packages.

### ISSUE THREAD

**Issue by ErickXMendez** [Jarli01/xenorchestra_installer#79]
Check your distribution respositories list ie: /etc/apt/sources.list for multiverse.

    build-essential
    redis-server
    libpng-dev
    git
    python-minimal
    libvhdi-utils
    nfs-common
    lvm2
    cifs-utils

These dependencies (on Ubuntu) are available from the multiverse and universe repositories.

How do I get those repositories? 
I tried using "sudo add-apt-repository universe" and the same with the multiverse but it's not integrated within xcp-ng. 

Is there any command I might have missed?

**I tried yum update but it's using the original xcp repo.

**Comment by Jarli01** [comment]
You DO NOT install XO on XCP-NG, you install XO as a VM on XCP-NG or XenServer, Please install a Ubuntu 20.04 VM and try the installation again using this script.

**Comment by Danp2** [comment]
In addition, you should remove any repos you enabled under XCP-NG. Otherwise, you may inadvertently install packages / updates that aren't compatible.

**Comment by ErickXMendez** [comment]
Thnaks Jarli01 and also Danp2 for the great help. 

Please consider pushing a  extra line saying that you need to create a vm on the xen server instead of directly running the code.

Thanks.

**Comment by Jarli01** [comment]
Happy to have helped.
