### ISSUE TITLE
Can I migrate existing configuration/setup?

### ISSUE THREAD

**Issue by tinjaw** [Jarli01/xenorchestra_installer#85]
I was using the commercial free-tier. I have now installed, and have a functioning, from-source XOA install.

The next step is the configuration. Do I need to start from scratch or can I export/import from the free-tier?

**Comment by Danp2** [comment]
Just export your config from XOA and then import it into your new XO VM

**Comment by tinjaw** [comment]
Worked perfectly. Thank you.
