### ISSUE TITLE
Wrong md5/sha256 checksum for prepackaged xoce.xva

### ISSUE THREAD

**Issue by marekm72** [Jarli01/xenorchestra_installer#86]
**Describe the bug**
Checksums of the downloaded xoce.xva don't match the ones in README.md

**To Reproduce**
The file was downloaded twice, via https and http to two different machines.
Both downloads have the same checksums (so no random corruption while downloading):

c9a14ced90bf7ea561d3055d5d1cc81c
c487d63f2eef67fcaf0e9c4e4998d4a3948fdad960cb1af5a70fcb80b07c2551

but these are different from the ones given in README.md:

8a982a08533800b4ca292e1525cf7b11
e0125f603ef15c08e9cc22c842c0c186c035d59fcea3c2becae88b5bc3a8c056

**Expected behavior**
Matching checksums.
Please check the hosted file to make sure it is not corrupted or compromised, or README.md just needs to be updated.

**Comment by Jarli01** [comment]
Sorry about that, was doing some changes, let me pull everything down and will update.

**Comment by Jarli01** [comment]
Just updated the read-me after pulling down the files. 

Thanks for the assist
