### ISSUE TITLE
Can't install yarn

### ISSUE THREAD

**Issue by jcdick1** [Jarli01/xenorchestra_installer#87]
I don't think this is strictly your problem, but I can't get yarn installed.  The script breaks because it can't get to dl.yarnpkg.com to install yarn.  Running apt update refreshes all of the Ubuntu repos, but dl.yarnpkg.com breaks the refresh.  Running "apt install yarn" gives "Note, selecting 'cmdtest' instead of 'yarn'"

Any insight is appreciated.

**Comment by Jarli01** [comment]
Sorry I hadn't seen this early, just checking to see if you actually resolved the issue?
