### ISSUE TITLE
Install questions

### ISSUE THREAD

**Issue by fagnerpatricio** [Jarli01/xenorchestra_installer#89]
Hi, great script, but i have two questions:
1 - this installation is safe to use in a production environment?
2 - Is any problem to use a debian install in a vSphere Hypervisor?

Thank you and great job

**Comment by Jarli01** [comment]
1 - This script automates the "build it yourself" approach that you can get from the XO documentation. It's perfectly safe to use in production. You'll of course have to support the installation yourself or with community supplied support. 

2 - You can absolutely install this into Debian on vSphere, there is no limitation where this is run from, so long as your XenServer or XCP-NG servers and XOCE are able to communicate with each other.

**Comment by Jarli01** [comment]
If you have any other questions just let us know. 

Thanks
