### ISSUE TITLE
Pool Shows 10 missing patches, but all patches are installed

### ISSUE THREAD

**Issue by BerT666** [Jarli01/xenorchestra_installer#90]
Hi,

since a few days I realized that there is an exclamation mark behind "Pools" (10 missing patches).
When I go to the Patches Section ( Pool or Hosts ) I am told that the systems are up to date. Regarding yum there are no patches left.
Is this just a display Bug, or something worser?

Best Thomas

![image](https://user-images.githubusercontent.com/23699624/98111311-b1b59480-1ea0-11eb-834c-38d7756f5c4c.png)
![image](https://user-images.githubusercontent.com/23699624/98111352-c3973780-1ea0-11eb-81b7-2b94b938e046.png)

**Comment by Jarli01** [comment]
This is very likely a display bug, but before we go and write it off have you restarted xo and xapi on you're servers?

**Comment by Jarli01** [comment]
Also are you keeping XOCE updated?

**Comment by BerT666** [comment]
Yes, I did restart the servers after installing the patches (first the master, afterwards the other nodes).
yes, in fact the last update of XOCE was done yesterday, but it did not change anything...

**Comment by Danp2** [comment]
What is your hypervisor version? Have you checked if XOA gives you the same info about missing patches?

**Comment by Jarli01** [comment]
> yes, in fact the last update of XOCE was done yesterday, but it did not change anything...

Did XOCE ask you to provide your github credentials or you're just current with the the XO branch?

**Comment by BerT666** [comment]
> > yes, in fact the last update of XOCE was done yesterday, but it did not change anything...
> 
> Did XOCE ask you to provide your github credentials or you're just current with the the XO branch?

Current to XO Branch

**Comment by Jarli01** [comment]
Okay, and to @Danp2 question, what is your hypervisor version listed as?

**Comment by BerT666** [comment]
sorry, the post with Hypervisor info was lost...

XCP-NG 8.1.0; release/quebec/master/17

**Comment by Jarli01** [comment]
This could possibly be the same as https://github.com/Jarli01/xenorchestra_installer/issues/90

The release has been out since January, so without more details I'd say verify that each host in the pool is updated.

**Comment by BerT666** [comment]
> This could possibly be the same as [vatesfr/xen-orchestra#4922](https://github.com/vatesfr/xen-orchestra/issues/4922)
> 
> The release has been out since January, so without more details I'd say verify that each host in the pool is updated.

By reading [vatesfr/xen-orchestra#4922](https://github.com/vatesfr/xen-orchestra/issues/4922) it sounds the same...

Like I said, yum also reports no missing patches => so it seems to be a display bug...

**Comment by Jarli01** [comment]
Can you try what's outline here on each of your hosts and see if one (or many servers in your pool) are out of date. 

https://github.com/vatesfr/xen-orchestra/issues/4922#issuecomment-617757292

**Comment by BerT666** [comment]
I installed xo-cli & tested the hosts with it ( regarding previous post) and now I found the missing patches ( the "last host" was missing patches).
Now the notification is vanished!
Thank you a lot!

**Comment by Jarli01** [comment]
Awesome, glad we were able to help get this sorted.
