### ISSUE TITLE
default credentials for ssh

### ISSUE THREAD

**Issue by jeebsion** [Jarli01/xenorchestra_installer#95]
I've installed xo through your bash script and managed to to into the xo dashboard with the admin@admin.net credential ... then I realized there's also ssh port running but trying the same credential won't do. What's the default login/pass for the xo-appliance vm?

**Comment by Jarli01** [comment]
SSH isn't configured on the appliance, if you setup XOCE on a system you installed yourself the creds would be whatever you used when you installed your server operating system.

If you installed SSH on the appliance, the userne would be XOCE, the default password configured is "xoce", bit you would've been forced to change this when logging in the first time

**Comment by jeebsion** [comment]
I deleted the vm and I did a reinstallation with the script at your page and the vm named now changed to "XOCE" instead of the previous name "xo-appliance" .. I guess you updated the image or something? and I saw the login/pass for the terminal is xoce/xoce ... then I found in the vm-list there're 4 vm by the name "XOCE" and only 1 running .. and I cannot get to the URL despite the IP configuration I configured earlier via the script.

Sorry it's kinda mouthful .. I wonder if I did something wrong here?

**Comment by Jarli01** [comment]
It sounds like you're trying to import the appliance you have to give it a few minutes in order to finish downloading, it's 1.6gb compressed. Depending how your internet performance. 

If you're using the installation script, you would have a brand new Ubuntu or Debian server that you'd run the installation on.

**Comment by jeebsion** [comment]
hrmm .. I've waited close to 45 minutes now ... should I try removing the vm and try again?

**Comment by jeebsion** [comment]
oh btw .. I restarted the box and the VMs earlier by the name "XOCE" now reduced to only 3 .. and all running .. I tried shutting down the VMs using xsconsole and each of 'em stop at 8% whilst shutting down. Such peculiar behavior really ...

**Comment by Jarli01** [comment]
How are you seeing these vm's? Please answer the template so I can better understand how you're setup.

**Comment by Jarli01** [comment]
If any of these vm's saying "importing" in their name, it means the import never completed. 

Can you answer the template questions and provide some screenshots of what you're seeing

**Comment by jeebsion** [comment]
Oh sorry .. I'm very new here .. what are template questions?

**Comment by Jarli01** [comment]
Take a look at the new ticket template, copy and paste and answer accordingly

**Comment by jeebsion** [comment]
sorry sir .. I am so lost .. I've tried searching for template all over this github profile to no avail :(

**Comment by jeebsion** [comment]
sorry sir .. I was running the script directly on my xcp-ng box ... maybe that's why it's not working?

**Comment by Jarli01** [comment]
It's prepopulated when you create a new issue case. 

In any scenario how did you install? 

Please attach screenshots bso I can see what you're seeing

**Comment by Jarli01** [comment]
> sorry sir .. I was running the script directly on my xcp-ng box ... maybe that's why it's not working?

Which script are you running? I have several listed on the main page.

**Comment by jeebsion** [comment]
I ran this command at prompt:

bash -c "$(curl -s https://raw.githubusercontent.com/Jarli01/xenorchestra_installer/master/xoce-import.sh)"

**Comment by Jarli01** [comment]
Ok so you're importing the appliance. 

Did you follow the on screen prompts?

**Comment by jeebsion** [comment]
yep .. the IP address configuration and that's that

**Comment by Jarli01** [comment]
So if the import finished (I'm assuming it has) when you go do the web address listed you can't login? 

Or are you asking what the credentials are to VM that you've imported, if this look at the instructions again, they're listed.

**Comment by jeebsion** [comment]
yes the import finished but I cannot get to the IP I entered earlier

**Comment by Jarli01** [comment]
You said you already deleted it. 

What desktop interface do you have? Windows?

**Comment by jeebsion** [comment]
yes deleted and run the script again .. 3 times in a row .. yes Windows 10

**Comment by Jarli01** [comment]
So you very likely have multiple imports attempting to take place. 

I'd record you download the xc-ng center agent, connect your server to it and see what is taking place.

https://github.com/xcp-ng/xenadmin

**Comment by jeebsion** [comment]
okay sir .. I think you can close this thread already .. if all fails today I'm gonna do a fresh install all over again .. tq sir!

**Comment by Jarli01** [comment]
No prob, you can also download the file directly over chrome or whatever browser you have and import it with XCP-NG Center.
