### ISSUE TITLE
Can't Login Through Root Password in SSH but XCP Center Works?

### ISSUE THREAD

**Issue by justingoldberg** [Jarli01/xenorchestra_installer#99]
For some reason I can get authenticate to the console as 'root' but not in putty. Do you have any idea about this? I am using Debian 10 on 64-bit.

#### Expected Behavior

Login to putty
-----

#### Actual Behavior

Access denied
-----

#### Confirm XOCE services are running

```systemctl status xo-server.service```

Running

#### Provide the output of journalctl logs

```journalctl -u xo-server -f -n 50```

#### What version of Node are you running?

```node -v```<br> 

14.17.4 LTS
 
#### Provide answers to these questions:

- Is this a fresh install or an upgrade? 
It is a fresh install using the script (after installing yarn and node and:
`build-essential redis-server libpng-dev git python-minimal libvhdi-utils lvm2 cifs-utils`

- Version of XOCE server and web interface you're running
- What OS is XOCE running on?
- What method you used to install XOCE (xo_install.sh, manual installation, etc)
- What specific XOCE page you're on, and what specific element you're interacting with to trigger the error
- If a stacktrace is provided in the error, include that too.
- Any errors that appear in your browser's error console.
- Include what you've done so far in the installation, and if you got any error messages along the way.
- Indicate whether or not you've manually edited any data directly.

Please do not post an issue without answering the related questions above. If you have opened a different issue and already answered these questions, answer them again, once for every ticket. It will be next to impossible for us to help you.

**Comment by Jarli01** [comment]
As this is before the installation process has occurred I can't answer for certain, since this was during "the installation of the OS" but my guess would be you need to look at editing /etc/ssh/sshd_config

**Comment by Jarli01** [comment]
I'm assuming you're all set and closing this. 

Good luck
